// Code generated by ent, DO NOT EDIT.

package revocation

import (
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/gm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldID, id))
}

// Proof applies equality check predicate on the "proof" field. It's identical to ProofEQ.
func Proof(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldProof, v))
}

// Nym applies equality check predicate on the "nym" field. It's identical to NymEQ.
func Nym(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldNym, v))
}

// Sigma applies equality check predicate on the "sigma" field. It's identical to SigmaEQ.
func Sigma(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldSigma, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldMessage, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldCount, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldPeriod, v))
}

// ProofEQ applies the EQ predicate on the "proof" field.
func ProofEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldProof, v))
}

// ProofNEQ applies the NEQ predicate on the "proof" field.
func ProofNEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldProof, v))
}

// ProofIn applies the In predicate on the "proof" field.
func ProofIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldProof, vs...))
}

// ProofNotIn applies the NotIn predicate on the "proof" field.
func ProofNotIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldProof, vs...))
}

// ProofGT applies the GT predicate on the "proof" field.
func ProofGT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldProof, v))
}

// ProofGTE applies the GTE predicate on the "proof" field.
func ProofGTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldProof, v))
}

// ProofLT applies the LT predicate on the "proof" field.
func ProofLT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldProof, v))
}

// ProofLTE applies the LTE predicate on the "proof" field.
func ProofLTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldProof, v))
}

// NymEQ applies the EQ predicate on the "nym" field.
func NymEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldNym, v))
}

// NymNEQ applies the NEQ predicate on the "nym" field.
func NymNEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldNym, v))
}

// NymIn applies the In predicate on the "nym" field.
func NymIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldNym, vs...))
}

// NymNotIn applies the NotIn predicate on the "nym" field.
func NymNotIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldNym, vs...))
}

// NymGT applies the GT predicate on the "nym" field.
func NymGT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldNym, v))
}

// NymGTE applies the GTE predicate on the "nym" field.
func NymGTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldNym, v))
}

// NymLT applies the LT predicate on the "nym" field.
func NymLT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldNym, v))
}

// NymLTE applies the LTE predicate on the "nym" field.
func NymLTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldNym, v))
}

// SigmaEQ applies the EQ predicate on the "sigma" field.
func SigmaEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldSigma, v))
}

// SigmaNEQ applies the NEQ predicate on the "sigma" field.
func SigmaNEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldSigma, v))
}

// SigmaIn applies the In predicate on the "sigma" field.
func SigmaIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldSigma, vs...))
}

// SigmaNotIn applies the NotIn predicate on the "sigma" field.
func SigmaNotIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldSigma, vs...))
}

// SigmaGT applies the GT predicate on the "sigma" field.
func SigmaGT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldSigma, v))
}

// SigmaGTE applies the GTE predicate on the "sigma" field.
func SigmaGTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldSigma, v))
}

// SigmaLT applies the LT predicate on the "sigma" field.
func SigmaLT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldSigma, v))
}

// SigmaLTE applies the LTE predicate on the "sigma" field.
func SigmaLTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldSigma, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldMessage, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldCount, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldPeriod, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.NotPredicates(p))
}
