// Code generated by ent, DO NOT EDIT.

package updateticket

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the updateticket type in the database.
	Label = "update_ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTicket holds the string denoting the ticket field in the database.
	FieldTicket = "ticket"
	// Table holds the table name of the updateticket in the database.
	Table = "update_tickets"
)

// Columns holds all SQL columns for updateticket fields.
var Columns = []string{
	FieldID,
	FieldTicket,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UpdateTicket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
