// Code generated by ent, DO NOT EDIT.

package updateticket

import (
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldLTE(FieldID, id))
}

// Ticket applies equality check predicate on the "ticket" field. It's identical to TicketEQ.
func Ticket(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldEQ(FieldTicket, v))
}

// TicketEQ applies the EQ predicate on the "ticket" field.
func TicketEQ(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldEQ(FieldTicket, v))
}

// TicketNEQ applies the NEQ predicate on the "ticket" field.
func TicketNEQ(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldNEQ(FieldTicket, v))
}

// TicketIn applies the In predicate on the "ticket" field.
func TicketIn(vs ...[]byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldIn(FieldTicket, vs...))
}

// TicketNotIn applies the NotIn predicate on the "ticket" field.
func TicketNotIn(vs ...[]byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldNotIn(FieldTicket, vs...))
}

// TicketGT applies the GT predicate on the "ticket" field.
func TicketGT(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldGT(FieldTicket, v))
}

// TicketGTE applies the GTE predicate on the "ticket" field.
func TicketGTE(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldGTE(FieldTicket, v))
}

// TicketLT applies the LT predicate on the "ticket" field.
func TicketLT(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldLT(FieldTicket, v))
}

// TicketLTE applies the LTE predicate on the "ticket" field.
func TicketLTE(v []byte) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.FieldLTE(FieldTicket, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpdateTicket) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpdateTicket) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpdateTicket) predicate.UpdateTicket {
	return predicate.UpdateTicket(sql.NotPredicates(p))
}
