// Code generated by ent, DO NOT EDIT.

package revocation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the revocation type in the database.
	Label = "revocation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNym holds the string denoting the nym field in the database.
	FieldNym = "nym"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldRevokedPeriod holds the string denoting the revoked_period field in the database.
	FieldRevokedPeriod = "revoked_period"
	// FieldSignedPeriod holds the string denoting the signed_period field in the database.
	FieldSignedPeriod = "signed_period"
	// Table holds the table name of the revocation in the database.
	Table = "revocations"
)

// Columns holds all SQL columns for revocation fields.
var Columns = []string{
	FieldID,
	FieldNym,
	FieldCount,
	FieldRevokedPeriod,
	FieldSignedPeriod,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Revocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// ByRevokedPeriod orders the results by the revoked_period field.
func ByRevokedPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedPeriod, opts...).ToFunc()
}

// BySignedPeriod orders the results by the signed_period field.
func BySignedPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignedPeriod, opts...).ToFunc()
}
