// Code generated by ent, DO NOT EDIT.

package revocation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the revocation type in the database.
	Label = "revocation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProof holds the string denoting the proof field in the database.
	FieldProof = "proof"
	// FieldNym holds the string denoting the nym field in the database.
	FieldNym = "nym"
	// FieldSigma holds the string denoting the sigma field in the database.
	FieldSigma = "sigma"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// Table holds the table name of the revocation in the database.
	Table = "revocations"
)

// Columns holds all SQL columns for revocation fields.
var Columns = []string{
	FieldID,
	FieldProof,
	FieldNym,
	FieldSigma,
	FieldMessage,
	FieldCount,
	FieldPeriod,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Revocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}
