// Code generated by ent, DO NOT EDIT.

package revocation

import (
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldID, id))
}

// Nym applies equality check predicate on the "nym" field. It's identical to NymEQ.
func Nym(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldNym, v))
}

// RevokedPeriod applies equality check predicate on the "revoked_period" field. It's identical to RevokedPeriodEQ.
func RevokedPeriod(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldRevokedPeriod, v))
}

// SignedPeriod applies equality check predicate on the "signed_period" field. It's identical to SignedPeriodEQ.
func SignedPeriod(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldSignedPeriod, v))
}

// NymEQ applies the EQ predicate on the "nym" field.
func NymEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldNym, v))
}

// NymNEQ applies the NEQ predicate on the "nym" field.
func NymNEQ(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldNym, v))
}

// NymIn applies the In predicate on the "nym" field.
func NymIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldNym, vs...))
}

// NymNotIn applies the NotIn predicate on the "nym" field.
func NymNotIn(vs ...[]byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldNym, vs...))
}

// NymGT applies the GT predicate on the "nym" field.
func NymGT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldNym, v))
}

// NymGTE applies the GTE predicate on the "nym" field.
func NymGTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldNym, v))
}

// NymLT applies the LT predicate on the "nym" field.
func NymLT(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldNym, v))
}

// NymLTE applies the LTE predicate on the "nym" field.
func NymLTE(v []byte) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldNym, v))
}

// RevokedPeriodEQ applies the EQ predicate on the "revoked_period" field.
func RevokedPeriodEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldRevokedPeriod, v))
}

// RevokedPeriodNEQ applies the NEQ predicate on the "revoked_period" field.
func RevokedPeriodNEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldRevokedPeriod, v))
}

// RevokedPeriodIn applies the In predicate on the "revoked_period" field.
func RevokedPeriodIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldRevokedPeriod, vs...))
}

// RevokedPeriodNotIn applies the NotIn predicate on the "revoked_period" field.
func RevokedPeriodNotIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldRevokedPeriod, vs...))
}

// RevokedPeriodGT applies the GT predicate on the "revoked_period" field.
func RevokedPeriodGT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldRevokedPeriod, v))
}

// RevokedPeriodGTE applies the GTE predicate on the "revoked_period" field.
func RevokedPeriodGTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldRevokedPeriod, v))
}

// RevokedPeriodLT applies the LT predicate on the "revoked_period" field.
func RevokedPeriodLT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldRevokedPeriod, v))
}

// RevokedPeriodLTE applies the LTE predicate on the "revoked_period" field.
func RevokedPeriodLTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldRevokedPeriod, v))
}

// SignedPeriodEQ applies the EQ predicate on the "signed_period" field.
func SignedPeriodEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldEQ(FieldSignedPeriod, v))
}

// SignedPeriodNEQ applies the NEQ predicate on the "signed_period" field.
func SignedPeriodNEQ(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNEQ(FieldSignedPeriod, v))
}

// SignedPeriodIn applies the In predicate on the "signed_period" field.
func SignedPeriodIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldIn(FieldSignedPeriod, vs...))
}

// SignedPeriodNotIn applies the NotIn predicate on the "signed_period" field.
func SignedPeriodNotIn(vs ...int) predicate.Revocation {
	return predicate.Revocation(sql.FieldNotIn(FieldSignedPeriod, vs...))
}

// SignedPeriodGT applies the GT predicate on the "signed_period" field.
func SignedPeriodGT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGT(FieldSignedPeriod, v))
}

// SignedPeriodGTE applies the GTE predicate on the "signed_period" field.
func SignedPeriodGTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldGTE(FieldSignedPeriod, v))
}

// SignedPeriodLT applies the LT predicate on the "signed_period" field.
func SignedPeriodLT(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLT(FieldSignedPeriod, v))
}

// SignedPeriodLTE applies the LTE predicate on the "signed_period" field.
func SignedPeriodLTE(v int) predicate.Revocation {
	return predicate.Revocation(sql.FieldLTE(FieldSignedPeriod, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Revocation) predicate.Revocation {
	return predicate.Revocation(sql.NotPredicates(p))
}
