// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/idtoken"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
)

// IDTokenQuery is the builder for querying IDToken entities.
type IDTokenQuery struct {
	config
	ctx        *QueryContext
	order      []idtoken.OrderOption
	inters     []Interceptor
	predicates []predicate.IDToken
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IDTokenQuery builder.
func (itq *IDTokenQuery) Where(ps ...predicate.IDToken) *IDTokenQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit the number of records to be returned by this query.
func (itq *IDTokenQuery) Limit(limit int) *IDTokenQuery {
	itq.ctx.Limit = &limit
	return itq
}

// Offset to start from.
func (itq *IDTokenQuery) Offset(offset int) *IDTokenQuery {
	itq.ctx.Offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *IDTokenQuery) Unique(unique bool) *IDTokenQuery {
	itq.ctx.Unique = &unique
	return itq
}

// Order specifies how the records should be ordered.
func (itq *IDTokenQuery) Order(o ...idtoken.OrderOption) *IDTokenQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// First returns the first IDToken entity from the query.
// Returns a *NotFoundError when no IDToken was found.
func (itq *IDTokenQuery) First(ctx context.Context) (*IDToken, error) {
	nodes, err := itq.Limit(1).All(setContextOp(ctx, itq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{idtoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *IDTokenQuery) FirstX(ctx context.Context) *IDToken {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IDToken ID from the query.
// Returns a *NotFoundError when no IDToken ID was found.
func (itq *IDTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(1).IDs(setContextOp(ctx, itq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{idtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *IDTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IDToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IDToken entity is found.
// Returns a *NotFoundError when no IDToken entities are found.
func (itq *IDTokenQuery) Only(ctx context.Context) (*IDToken, error) {
	nodes, err := itq.Limit(2).All(setContextOp(ctx, itq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{idtoken.Label}
	default:
		return nil, &NotSingularError{idtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *IDTokenQuery) OnlyX(ctx context.Context) *IDToken {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IDToken ID in the query.
// Returns a *NotSingularError when more than one IDToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (itq *IDTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(2).IDs(setContextOp(ctx, itq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{idtoken.Label}
	default:
		err = &NotSingularError{idtoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *IDTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IDTokens.
func (itq *IDTokenQuery) All(ctx context.Context) ([]*IDToken, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryAll)
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IDToken, *IDTokenQuery]()
	return withInterceptors[[]*IDToken](ctx, itq, qr, itq.inters)
}

// AllX is like All, but panics if an error occurs.
func (itq *IDTokenQuery) AllX(ctx context.Context) []*IDToken {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IDToken IDs.
func (itq *IDTokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if itq.ctx.Unique == nil && itq.path != nil {
		itq.Unique(true)
	}
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryIDs)
	if err = itq.Select(idtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *IDTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *IDTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryCount)
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, itq, querierCount[*IDTokenQuery](), itq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (itq *IDTokenQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *IDTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, itq.ctx, ent.OpQueryExist)
	switch _, err := itq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *IDTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IDTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *IDTokenQuery) Clone() *IDTokenQuery {
	if itq == nil {
		return nil
	}
	return &IDTokenQuery{
		config:     itq.config,
		ctx:        itq.ctx.Clone(),
		order:      append([]idtoken.OrderOption{}, itq.order...),
		inters:     append([]Interceptor{}, itq.inters...),
		predicates: append([]predicate.IDToken{}, itq.predicates...),
		// clone intermediate query.
		sql:  itq.sql.Clone(),
		path: itq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IdToken string `json:"idToken,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IDToken.Query().
//		GroupBy(idtoken.FieldIdToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (itq *IDTokenQuery) GroupBy(field string, fields ...string) *IDTokenGroupBy {
	itq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IDTokenGroupBy{build: itq}
	grbuild.flds = &itq.ctx.Fields
	grbuild.label = idtoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IdToken string `json:"idToken,omitempty"`
//	}
//
//	client.IDToken.Query().
//		Select(idtoken.FieldIdToken).
//		Scan(ctx, &v)
func (itq *IDTokenQuery) Select(fields ...string) *IDTokenSelect {
	itq.ctx.Fields = append(itq.ctx.Fields, fields...)
	sbuild := &IDTokenSelect{IDTokenQuery: itq}
	sbuild.label = idtoken.Label
	sbuild.flds, sbuild.scan = &itq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IDTokenSelect configured with the given aggregations.
func (itq *IDTokenQuery) Aggregate(fns ...AggregateFunc) *IDTokenSelect {
	return itq.Select().Aggregate(fns...)
}

func (itq *IDTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range itq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, itq); err != nil {
				return err
			}
		}
	}
	for _, f := range itq.ctx.Fields {
		if !idtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *IDTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IDToken, error) {
	var (
		nodes = []*IDToken{}
		_spec = itq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IDToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IDToken{config: itq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (itq *IDTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	_spec.Node.Columns = itq.ctx.Fields
	if len(itq.ctx.Fields) > 0 {
		_spec.Unique = itq.ctx.Unique != nil && *itq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *IDTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(idtoken.Table, idtoken.Columns, sqlgraph.NewFieldSpec(idtoken.FieldID, field.TypeInt))
	_spec.From = itq.sql
	if unique := itq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if itq.path != nil {
		_spec.Unique = true
	}
	if fields := itq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idtoken.FieldID)
		for i := range fields {
			if fields[i] != idtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *IDTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(idtoken.Table)
	columns := itq.ctx.Fields
	if len(columns) == 0 {
		columns = idtoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if itq.ctx.Unique != nil && *itq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IDTokenGroupBy is the group-by builder for IDToken entities.
type IDTokenGroupBy struct {
	selector
	build *IDTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *IDTokenGroupBy) Aggregate(fns ...AggregateFunc) *IDTokenGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the selector query and scans the result into the given value.
func (itgb *IDTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, itgb.build.ctx, ent.OpQueryGroupBy)
	if err := itgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IDTokenQuery, *IDTokenGroupBy](ctx, itgb.build, itgb, itgb.build.inters, v)
}

func (itgb *IDTokenGroupBy) sqlScan(ctx context.Context, root *IDTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(itgb.fns))
	for _, fn := range itgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*itgb.flds)+len(itgb.fns))
		for _, f := range *itgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*itgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IDTokenSelect is the builder for selecting fields of IDToken entities.
type IDTokenSelect struct {
	*IDTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (its *IDTokenSelect) Aggregate(fns ...AggregateFunc) *IDTokenSelect {
	its.fns = append(its.fns, fns...)
	return its
}

// Scan applies the selector query and scans the result into the given value.
func (its *IDTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, its.ctx, ent.OpQuerySelect)
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IDTokenQuery, *IDTokenSelect](ctx, its.IDTokenQuery, its, its.inters, v)
}

func (its *IDTokenSelect) sqlScan(ctx context.Context, root *IDTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(its.fns))
	for _, fn := range its.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*its.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
