// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/idtoken"
)

// IDTokenCreate is the builder for creating a IDToken entity.
type IDTokenCreate struct {
	config
	mutation *IDTokenMutation
	hooks    []Hook
}

// SetIdToken sets the "idToken" field.
func (itc *IDTokenCreate) SetIdToken(s string) *IDTokenCreate {
	itc.mutation.SetIdToken(s)
	return itc
}

// Mutation returns the IDTokenMutation object of the builder.
func (itc *IDTokenCreate) Mutation() *IDTokenMutation {
	return itc.mutation
}

// Save creates the IDToken in the database.
func (itc *IDTokenCreate) Save(ctx context.Context) (*IDToken, error) {
	return withHooks(ctx, itc.sqlSave, itc.mutation, itc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (itc *IDTokenCreate) SaveX(ctx context.Context) *IDToken {
	v, err := itc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (itc *IDTokenCreate) Exec(ctx context.Context) error {
	_, err := itc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itc *IDTokenCreate) ExecX(ctx context.Context) {
	if err := itc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (itc *IDTokenCreate) check() error {
	if _, ok := itc.mutation.IdToken(); !ok {
		return &ValidationError{Name: "idToken", err: errors.New(`ent: missing required field "IDToken.idToken"`)}
	}
	return nil
}

func (itc *IDTokenCreate) sqlSave(ctx context.Context) (*IDToken, error) {
	if err := itc.check(); err != nil {
		return nil, err
	}
	_node, _spec := itc.createSpec()
	if err := sqlgraph.CreateNode(ctx, itc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	itc.mutation.id = &_node.ID
	itc.mutation.done = true
	return _node, nil
}

func (itc *IDTokenCreate) createSpec() (*IDToken, *sqlgraph.CreateSpec) {
	var (
		_node = &IDToken{config: itc.config}
		_spec = sqlgraph.NewCreateSpec(idtoken.Table, sqlgraph.NewFieldSpec(idtoken.FieldID, field.TypeInt))
	)
	if value, ok := itc.mutation.IdToken(); ok {
		_spec.SetField(idtoken.FieldIdToken, field.TypeString, value)
		_node.IdToken = value
	}
	return _node, _spec
}

// IDTokenCreateBulk is the builder for creating many IDToken entities in bulk.
type IDTokenCreateBulk struct {
	config
	err      error
	builders []*IDTokenCreate
}

// Save creates the IDToken entities in the database.
func (itcb *IDTokenCreateBulk) Save(ctx context.Context) ([]*IDToken, error) {
	if itcb.err != nil {
		return nil, itcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(itcb.builders))
	nodes := make([]*IDToken, len(itcb.builders))
	mutators := make([]Mutator, len(itcb.builders))
	for i := range itcb.builders {
		func(i int, root context.Context) {
			builder := itcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IDTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, itcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, itcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, itcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (itcb *IDTokenCreateBulk) SaveX(ctx context.Context) []*IDToken {
	v, err := itcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (itcb *IDTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := itcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itcb *IDTokenCreateBulk) ExecX(ctx context.Context) {
	if err := itcb.Exec(ctx); err != nil {
		panic(err)
	}
}
