// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/idtoken"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
)

// IDTokenUpdate is the builder for updating IDToken entities.
type IDTokenUpdate struct {
	config
	hooks    []Hook
	mutation *IDTokenMutation
}

// Where appends a list predicates to the IDTokenUpdate builder.
func (itu *IDTokenUpdate) Where(ps ...predicate.IDToken) *IDTokenUpdate {
	itu.mutation.Where(ps...)
	return itu
}

// SetIdToken sets the "idToken" field.
func (itu *IDTokenUpdate) SetIdToken(s string) *IDTokenUpdate {
	itu.mutation.SetIdToken(s)
	return itu
}

// SetNillableIdToken sets the "idToken" field if the given value is not nil.
func (itu *IDTokenUpdate) SetNillableIdToken(s *string) *IDTokenUpdate {
	if s != nil {
		itu.SetIdToken(*s)
	}
	return itu
}

// Mutation returns the IDTokenMutation object of the builder.
func (itu *IDTokenUpdate) Mutation() *IDTokenMutation {
	return itu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (itu *IDTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, itu.sqlSave, itu.mutation, itu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (itu *IDTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := itu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (itu *IDTokenUpdate) Exec(ctx context.Context) error {
	_, err := itu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itu *IDTokenUpdate) ExecX(ctx context.Context) {
	if err := itu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (itu *IDTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(idtoken.Table, idtoken.Columns, sqlgraph.NewFieldSpec(idtoken.FieldID, field.TypeInt))
	if ps := itu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := itu.mutation.IdToken(); ok {
		_spec.SetField(idtoken.FieldIdToken, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, itu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	itu.mutation.done = true
	return n, nil
}

// IDTokenUpdateOne is the builder for updating a single IDToken entity.
type IDTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IDTokenMutation
}

// SetIdToken sets the "idToken" field.
func (ituo *IDTokenUpdateOne) SetIdToken(s string) *IDTokenUpdateOne {
	ituo.mutation.SetIdToken(s)
	return ituo
}

// SetNillableIdToken sets the "idToken" field if the given value is not nil.
func (ituo *IDTokenUpdateOne) SetNillableIdToken(s *string) *IDTokenUpdateOne {
	if s != nil {
		ituo.SetIdToken(*s)
	}
	return ituo
}

// Mutation returns the IDTokenMutation object of the builder.
func (ituo *IDTokenUpdateOne) Mutation() *IDTokenMutation {
	return ituo.mutation
}

// Where appends a list predicates to the IDTokenUpdate builder.
func (ituo *IDTokenUpdateOne) Where(ps ...predicate.IDToken) *IDTokenUpdateOne {
	ituo.mutation.Where(ps...)
	return ituo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ituo *IDTokenUpdateOne) Select(field string, fields ...string) *IDTokenUpdateOne {
	ituo.fields = append([]string{field}, fields...)
	return ituo
}

// Save executes the query and returns the updated IDToken entity.
func (ituo *IDTokenUpdateOne) Save(ctx context.Context) (*IDToken, error) {
	return withHooks(ctx, ituo.sqlSave, ituo.mutation, ituo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ituo *IDTokenUpdateOne) SaveX(ctx context.Context) *IDToken {
	node, err := ituo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ituo *IDTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := ituo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ituo *IDTokenUpdateOne) ExecX(ctx context.Context) {
	if err := ituo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ituo *IDTokenUpdateOne) sqlSave(ctx context.Context) (_node *IDToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(idtoken.Table, idtoken.Columns, sqlgraph.NewFieldSpec(idtoken.FieldID, field.TypeInt))
	id, ok := ituo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IDToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ituo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idtoken.FieldID)
		for _, f := range fields {
			if !idtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ituo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ituo.mutation.IdToken(); ok {
		_spec.SetField(idtoken.FieldIdToken, field.TypeString, value)
	}
	_node = &IDToken{config: ituo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ituo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ituo.mutation.done = true
	return _node, nil
}
