// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/gm/ent/idtoken"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
	"github.com/akakou/zk-ban-system/core/gm/ent/revocation"
	"github.com/akakou/zk-ban-system/core/gm/ent/updateticket"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeIDToken      = "IDToken"
	TypeRevocation   = "Revocation"
	TypeUpdateTicket = "UpdateTicket"
)

// IDTokenMutation represents an operation that mutates the IDToken nodes in the graph.
type IDTokenMutation struct {
	config
	op            Op
	typ           string
	id            *int
	idToken       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*IDToken, error)
	predicates    []predicate.IDToken
}

var _ ent.Mutation = (*IDTokenMutation)(nil)

// idtokenOption allows management of the mutation configuration using functional options.
type idtokenOption func(*IDTokenMutation)

// newIDTokenMutation creates new mutation for the IDToken entity.
func newIDTokenMutation(c config, op Op, opts ...idtokenOption) *IDTokenMutation {
	m := &IDTokenMutation{
		config:        c,
		op:            op,
		typ:           TypeIDToken,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withIDTokenID sets the ID field of the mutation.
func withIDTokenID(id int) idtokenOption {
	return func(m *IDTokenMutation) {
		var (
			err   error
			once  sync.Once
			value *IDToken
		)
		m.oldValue = func(ctx context.Context) (*IDToken, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().IDToken.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withIDToken sets the old IDToken of the mutation.
func withIDToken(node *IDToken) idtokenOption {
	return func(m *IDTokenMutation) {
		m.oldValue = func(context.Context) (*IDToken, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m IDTokenMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m IDTokenMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *IDTokenMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *IDTokenMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().IDToken.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIdToken sets the "idToken" field.
func (m *IDTokenMutation) SetIdToken(s string) {
	m.idToken = &s
}

// IdToken returns the value of the "idToken" field in the mutation.
func (m *IDTokenMutation) IdToken() (r string, exists bool) {
	v := m.idToken
	if v == nil {
		return
	}
	return *v, true
}

// OldIdToken returns the old "idToken" field's value of the IDToken entity.
// If the IDToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *IDTokenMutation) OldIdToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIdToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIdToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIdToken: %w", err)
	}
	return oldValue.IdToken, nil
}

// ResetIdToken resets all changes to the "idToken" field.
func (m *IDTokenMutation) ResetIdToken() {
	m.idToken = nil
}

// Where appends a list predicates to the IDTokenMutation builder.
func (m *IDTokenMutation) Where(ps ...predicate.IDToken) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the IDTokenMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *IDTokenMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.IDToken, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *IDTokenMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *IDTokenMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (IDToken).
func (m *IDTokenMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *IDTokenMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.idToken != nil {
		fields = append(fields, idtoken.FieldIdToken)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *IDTokenMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case idtoken.FieldIdToken:
		return m.IdToken()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *IDTokenMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case idtoken.FieldIdToken:
		return m.OldIdToken(ctx)
	}
	return nil, fmt.Errorf("unknown IDToken field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *IDTokenMutation) SetField(name string, value ent.Value) error {
	switch name {
	case idtoken.FieldIdToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIdToken(v)
		return nil
	}
	return fmt.Errorf("unknown IDToken field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *IDTokenMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *IDTokenMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *IDTokenMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown IDToken numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *IDTokenMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *IDTokenMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *IDTokenMutation) ClearField(name string) error {
	return fmt.Errorf("unknown IDToken nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *IDTokenMutation) ResetField(name string) error {
	switch name {
	case idtoken.FieldIdToken:
		m.ResetIdToken()
		return nil
	}
	return fmt.Errorf("unknown IDToken field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *IDTokenMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *IDTokenMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *IDTokenMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *IDTokenMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *IDTokenMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *IDTokenMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *IDTokenMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown IDToken unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *IDTokenMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown IDToken edge %s", name)
}

// RevocationMutation represents an operation that mutates the Revocation nodes in the graph.
type RevocationMutation struct {
	config
	op                Op
	typ               string
	id                *int
	nym               *[]byte
	count             *int
	addcount          *int
	revoked_period    *int
	addrevoked_period *int
	signed_period     *int
	addsigned_period  *int
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Revocation, error)
	predicates        []predicate.Revocation
}

var _ ent.Mutation = (*RevocationMutation)(nil)

// revocationOption allows management of the mutation configuration using functional options.
type revocationOption func(*RevocationMutation)

// newRevocationMutation creates new mutation for the Revocation entity.
func newRevocationMutation(c config, op Op, opts ...revocationOption) *RevocationMutation {
	m := &RevocationMutation{
		config:        c,
		op:            op,
		typ:           TypeRevocation,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRevocationID sets the ID field of the mutation.
func withRevocationID(id int) revocationOption {
	return func(m *RevocationMutation) {
		var (
			err   error
			once  sync.Once
			value *Revocation
		)
		m.oldValue = func(ctx context.Context) (*Revocation, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Revocation.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRevocation sets the old Revocation of the mutation.
func withRevocation(node *Revocation) revocationOption {
	return func(m *RevocationMutation) {
		m.oldValue = func(context.Context) (*Revocation, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RevocationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RevocationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RevocationMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RevocationMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Revocation.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNym sets the "nym" field.
func (m *RevocationMutation) SetNym(b []byte) {
	m.nym = &b
}

// Nym returns the value of the "nym" field in the mutation.
func (m *RevocationMutation) Nym() (r []byte, exists bool) {
	v := m.nym
	if v == nil {
		return
	}
	return *v, true
}

// OldNym returns the old "nym" field's value of the Revocation entity.
// If the Revocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RevocationMutation) OldNym(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNym is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNym requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNym: %w", err)
	}
	return oldValue.Nym, nil
}

// ResetNym resets all changes to the "nym" field.
func (m *RevocationMutation) ResetNym() {
	m.nym = nil
}

// SetCount sets the "count" field.
func (m *RevocationMutation) SetCount(i int) {
	m.count = &i
	m.addcount = nil
}

// Count returns the value of the "count" field in the mutation.
func (m *RevocationMutation) Count() (r int, exists bool) {
	v := m.count
	if v == nil {
		return
	}
	return *v, true
}

// OldCount returns the old "count" field's value of the Revocation entity.
// If the Revocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RevocationMutation) OldCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCount: %w", err)
	}
	return oldValue.Count, nil
}

// AddCount adds i to the "count" field.
func (m *RevocationMutation) AddCount(i int) {
	if m.addcount != nil {
		*m.addcount += i
	} else {
		m.addcount = &i
	}
}

// AddedCount returns the value that was added to the "count" field in this mutation.
func (m *RevocationMutation) AddedCount() (r int, exists bool) {
	v := m.addcount
	if v == nil {
		return
	}
	return *v, true
}

// ResetCount resets all changes to the "count" field.
func (m *RevocationMutation) ResetCount() {
	m.count = nil
	m.addcount = nil
}

// SetRevokedPeriod sets the "revoked_period" field.
func (m *RevocationMutation) SetRevokedPeriod(i int) {
	m.revoked_period = &i
	m.addrevoked_period = nil
}

// RevokedPeriod returns the value of the "revoked_period" field in the mutation.
func (m *RevocationMutation) RevokedPeriod() (r int, exists bool) {
	v := m.revoked_period
	if v == nil {
		return
	}
	return *v, true
}

// OldRevokedPeriod returns the old "revoked_period" field's value of the Revocation entity.
// If the Revocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RevocationMutation) OldRevokedPeriod(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRevokedPeriod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRevokedPeriod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRevokedPeriod: %w", err)
	}
	return oldValue.RevokedPeriod, nil
}

// AddRevokedPeriod adds i to the "revoked_period" field.
func (m *RevocationMutation) AddRevokedPeriod(i int) {
	if m.addrevoked_period != nil {
		*m.addrevoked_period += i
	} else {
		m.addrevoked_period = &i
	}
}

// AddedRevokedPeriod returns the value that was added to the "revoked_period" field in this mutation.
func (m *RevocationMutation) AddedRevokedPeriod() (r int, exists bool) {
	v := m.addrevoked_period
	if v == nil {
		return
	}
	return *v, true
}

// ResetRevokedPeriod resets all changes to the "revoked_period" field.
func (m *RevocationMutation) ResetRevokedPeriod() {
	m.revoked_period = nil
	m.addrevoked_period = nil
}

// SetSignedPeriod sets the "signed_period" field.
func (m *RevocationMutation) SetSignedPeriod(i int) {
	m.signed_period = &i
	m.addsigned_period = nil
}

// SignedPeriod returns the value of the "signed_period" field in the mutation.
func (m *RevocationMutation) SignedPeriod() (r int, exists bool) {
	v := m.signed_period
	if v == nil {
		return
	}
	return *v, true
}

// OldSignedPeriod returns the old "signed_period" field's value of the Revocation entity.
// If the Revocation object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RevocationMutation) OldSignedPeriod(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSignedPeriod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSignedPeriod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSignedPeriod: %w", err)
	}
	return oldValue.SignedPeriod, nil
}

// AddSignedPeriod adds i to the "signed_period" field.
func (m *RevocationMutation) AddSignedPeriod(i int) {
	if m.addsigned_period != nil {
		*m.addsigned_period += i
	} else {
		m.addsigned_period = &i
	}
}

// AddedSignedPeriod returns the value that was added to the "signed_period" field in this mutation.
func (m *RevocationMutation) AddedSignedPeriod() (r int, exists bool) {
	v := m.addsigned_period
	if v == nil {
		return
	}
	return *v, true
}

// ResetSignedPeriod resets all changes to the "signed_period" field.
func (m *RevocationMutation) ResetSignedPeriod() {
	m.signed_period = nil
	m.addsigned_period = nil
}

// Where appends a list predicates to the RevocationMutation builder.
func (m *RevocationMutation) Where(ps ...predicate.Revocation) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RevocationMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RevocationMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Revocation, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RevocationMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RevocationMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Revocation).
func (m *RevocationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RevocationMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.nym != nil {
		fields = append(fields, revocation.FieldNym)
	}
	if m.count != nil {
		fields = append(fields, revocation.FieldCount)
	}
	if m.revoked_period != nil {
		fields = append(fields, revocation.FieldRevokedPeriod)
	}
	if m.signed_period != nil {
		fields = append(fields, revocation.FieldSignedPeriod)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RevocationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case revocation.FieldNym:
		return m.Nym()
	case revocation.FieldCount:
		return m.Count()
	case revocation.FieldRevokedPeriod:
		return m.RevokedPeriod()
	case revocation.FieldSignedPeriod:
		return m.SignedPeriod()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RevocationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case revocation.FieldNym:
		return m.OldNym(ctx)
	case revocation.FieldCount:
		return m.OldCount(ctx)
	case revocation.FieldRevokedPeriod:
		return m.OldRevokedPeriod(ctx)
	case revocation.FieldSignedPeriod:
		return m.OldSignedPeriod(ctx)
	}
	return nil, fmt.Errorf("unknown Revocation field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RevocationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case revocation.FieldNym:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNym(v)
		return nil
	case revocation.FieldCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCount(v)
		return nil
	case revocation.FieldRevokedPeriod:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRevokedPeriod(v)
		return nil
	case revocation.FieldSignedPeriod:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSignedPeriod(v)
		return nil
	}
	return fmt.Errorf("unknown Revocation field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RevocationMutation) AddedFields() []string {
	var fields []string
	if m.addcount != nil {
		fields = append(fields, revocation.FieldCount)
	}
	if m.addrevoked_period != nil {
		fields = append(fields, revocation.FieldRevokedPeriod)
	}
	if m.addsigned_period != nil {
		fields = append(fields, revocation.FieldSignedPeriod)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RevocationMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case revocation.FieldCount:
		return m.AddedCount()
	case revocation.FieldRevokedPeriod:
		return m.AddedRevokedPeriod()
	case revocation.FieldSignedPeriod:
		return m.AddedSignedPeriod()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RevocationMutation) AddField(name string, value ent.Value) error {
	switch name {
	case revocation.FieldCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCount(v)
		return nil
	case revocation.FieldRevokedPeriod:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRevokedPeriod(v)
		return nil
	case revocation.FieldSignedPeriod:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSignedPeriod(v)
		return nil
	}
	return fmt.Errorf("unknown Revocation numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RevocationMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RevocationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RevocationMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Revocation nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RevocationMutation) ResetField(name string) error {
	switch name {
	case revocation.FieldNym:
		m.ResetNym()
		return nil
	case revocation.FieldCount:
		m.ResetCount()
		return nil
	case revocation.FieldRevokedPeriod:
		m.ResetRevokedPeriod()
		return nil
	case revocation.FieldSignedPeriod:
		m.ResetSignedPeriod()
		return nil
	}
	return fmt.Errorf("unknown Revocation field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RevocationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RevocationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RevocationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RevocationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RevocationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RevocationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RevocationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Revocation unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RevocationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Revocation edge %s", name)
}

// UpdateTicketMutation represents an operation that mutates the UpdateTicket nodes in the graph.
type UpdateTicketMutation struct {
	config
	op            Op
	typ           string
	id            *int
	ticket        *[]byte
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UpdateTicket, error)
	predicates    []predicate.UpdateTicket
}

var _ ent.Mutation = (*UpdateTicketMutation)(nil)

// updateticketOption allows management of the mutation configuration using functional options.
type updateticketOption func(*UpdateTicketMutation)

// newUpdateTicketMutation creates new mutation for the UpdateTicket entity.
func newUpdateTicketMutation(c config, op Op, opts ...updateticketOption) *UpdateTicketMutation {
	m := &UpdateTicketMutation{
		config:        c,
		op:            op,
		typ:           TypeUpdateTicket,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUpdateTicketID sets the ID field of the mutation.
func withUpdateTicketID(id int) updateticketOption {
	return func(m *UpdateTicketMutation) {
		var (
			err   error
			once  sync.Once
			value *UpdateTicket
		)
		m.oldValue = func(ctx context.Context) (*UpdateTicket, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UpdateTicket.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUpdateTicket sets the old UpdateTicket of the mutation.
func withUpdateTicket(node *UpdateTicket) updateticketOption {
	return func(m *UpdateTicketMutation) {
		m.oldValue = func(context.Context) (*UpdateTicket, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UpdateTicketMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UpdateTicketMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UpdateTicketMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UpdateTicketMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UpdateTicket.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTicket sets the "ticket" field.
func (m *UpdateTicketMutation) SetTicket(b []byte) {
	m.ticket = &b
}

// Ticket returns the value of the "ticket" field in the mutation.
func (m *UpdateTicketMutation) Ticket() (r []byte, exists bool) {
	v := m.ticket
	if v == nil {
		return
	}
	return *v, true
}

// OldTicket returns the old "ticket" field's value of the UpdateTicket entity.
// If the UpdateTicket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UpdateTicketMutation) OldTicket(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTicket is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTicket requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTicket: %w", err)
	}
	return oldValue.Ticket, nil
}

// ResetTicket resets all changes to the "ticket" field.
func (m *UpdateTicketMutation) ResetTicket() {
	m.ticket = nil
}

// Where appends a list predicates to the UpdateTicketMutation builder.
func (m *UpdateTicketMutation) Where(ps ...predicate.UpdateTicket) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UpdateTicketMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UpdateTicketMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UpdateTicket, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UpdateTicketMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UpdateTicketMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UpdateTicket).
func (m *UpdateTicketMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UpdateTicketMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.ticket != nil {
		fields = append(fields, updateticket.FieldTicket)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UpdateTicketMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case updateticket.FieldTicket:
		return m.Ticket()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UpdateTicketMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case updateticket.FieldTicket:
		return m.OldTicket(ctx)
	}
	return nil, fmt.Errorf("unknown UpdateTicket field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UpdateTicketMutation) SetField(name string, value ent.Value) error {
	switch name {
	case updateticket.FieldTicket:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTicket(v)
		return nil
	}
	return fmt.Errorf("unknown UpdateTicket field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UpdateTicketMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UpdateTicketMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UpdateTicketMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UpdateTicket numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UpdateTicketMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UpdateTicketMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UpdateTicketMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UpdateTicket nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UpdateTicketMutation) ResetField(name string) error {
	switch name {
	case updateticket.FieldTicket:
		m.ResetTicket()
		return nil
	}
	return fmt.Errorf("unknown UpdateTicket field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UpdateTicketMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UpdateTicketMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UpdateTicketMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UpdateTicketMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UpdateTicketMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UpdateTicketMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UpdateTicketMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UpdateTicket unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UpdateTicketMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UpdateTicket edge %s", name)
}
