// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
	"github.com/akakou/zk-ban-system/core/gm/ent/revocation"
)

// RevocationUpdate is the builder for updating Revocation entities.
type RevocationUpdate struct {
	config
	hooks    []Hook
	mutation *RevocationMutation
}

// Where appends a list predicates to the RevocationUpdate builder.
func (ru *RevocationUpdate) Where(ps ...predicate.Revocation) *RevocationUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetProof sets the "proof" field.
func (ru *RevocationUpdate) SetProof(b []byte) *RevocationUpdate {
	ru.mutation.SetProof(b)
	return ru
}

// SetNym sets the "nym" field.
func (ru *RevocationUpdate) SetNym(b []byte) *RevocationUpdate {
	ru.mutation.SetNym(b)
	return ru
}

// SetSigma sets the "sigma" field.
func (ru *RevocationUpdate) SetSigma(b []byte) *RevocationUpdate {
	ru.mutation.SetSigma(b)
	return ru
}

// SetMessage sets the "message" field.
func (ru *RevocationUpdate) SetMessage(b []byte) *RevocationUpdate {
	ru.mutation.SetMessage(b)
	return ru
}

// SetCount sets the "count" field.
func (ru *RevocationUpdate) SetCount(i int) *RevocationUpdate {
	ru.mutation.ResetCount()
	ru.mutation.SetCount(i)
	return ru
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (ru *RevocationUpdate) SetNillableCount(i *int) *RevocationUpdate {
	if i != nil {
		ru.SetCount(*i)
	}
	return ru
}

// AddCount adds i to the "count" field.
func (ru *RevocationUpdate) AddCount(i int) *RevocationUpdate {
	ru.mutation.AddCount(i)
	return ru
}

// SetPeriod sets the "period" field.
func (ru *RevocationUpdate) SetPeriod(i int) *RevocationUpdate {
	ru.mutation.ResetPeriod()
	ru.mutation.SetPeriod(i)
	return ru
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (ru *RevocationUpdate) SetNillablePeriod(i *int) *RevocationUpdate {
	if i != nil {
		ru.SetPeriod(*i)
	}
	return ru
}

// AddPeriod adds i to the "period" field.
func (ru *RevocationUpdate) AddPeriod(i int) *RevocationUpdate {
	ru.mutation.AddPeriod(i)
	return ru
}

// Mutation returns the RevocationMutation object of the builder.
func (ru *RevocationUpdate) Mutation() *RevocationMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RevocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RevocationUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RevocationUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RevocationUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RevocationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(revocation.Table, revocation.Columns, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Proof(); ok {
		_spec.SetField(revocation.FieldProof, field.TypeBytes, value)
	}
	if value, ok := ru.mutation.Nym(); ok {
		_spec.SetField(revocation.FieldNym, field.TypeBytes, value)
	}
	if value, ok := ru.mutation.Sigma(); ok {
		_spec.SetField(revocation.FieldSigma, field.TypeBytes, value)
	}
	if value, ok := ru.mutation.Message(); ok {
		_spec.SetField(revocation.FieldMessage, field.TypeBytes, value)
	}
	if value, ok := ru.mutation.Count(); ok {
		_spec.SetField(revocation.FieldCount, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedCount(); ok {
		_spec.AddField(revocation.FieldCount, field.TypeInt, value)
	}
	if value, ok := ru.mutation.Period(); ok {
		_spec.SetField(revocation.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedPeriod(); ok {
		_spec.AddField(revocation.FieldPeriod, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RevocationUpdateOne is the builder for updating a single Revocation entity.
type RevocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RevocationMutation
}

// SetProof sets the "proof" field.
func (ruo *RevocationUpdateOne) SetProof(b []byte) *RevocationUpdateOne {
	ruo.mutation.SetProof(b)
	return ruo
}

// SetNym sets the "nym" field.
func (ruo *RevocationUpdateOne) SetNym(b []byte) *RevocationUpdateOne {
	ruo.mutation.SetNym(b)
	return ruo
}

// SetSigma sets the "sigma" field.
func (ruo *RevocationUpdateOne) SetSigma(b []byte) *RevocationUpdateOne {
	ruo.mutation.SetSigma(b)
	return ruo
}

// SetMessage sets the "message" field.
func (ruo *RevocationUpdateOne) SetMessage(b []byte) *RevocationUpdateOne {
	ruo.mutation.SetMessage(b)
	return ruo
}

// SetCount sets the "count" field.
func (ruo *RevocationUpdateOne) SetCount(i int) *RevocationUpdateOne {
	ruo.mutation.ResetCount()
	ruo.mutation.SetCount(i)
	return ruo
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (ruo *RevocationUpdateOne) SetNillableCount(i *int) *RevocationUpdateOne {
	if i != nil {
		ruo.SetCount(*i)
	}
	return ruo
}

// AddCount adds i to the "count" field.
func (ruo *RevocationUpdateOne) AddCount(i int) *RevocationUpdateOne {
	ruo.mutation.AddCount(i)
	return ruo
}

// SetPeriod sets the "period" field.
func (ruo *RevocationUpdateOne) SetPeriod(i int) *RevocationUpdateOne {
	ruo.mutation.ResetPeriod()
	ruo.mutation.SetPeriod(i)
	return ruo
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (ruo *RevocationUpdateOne) SetNillablePeriod(i *int) *RevocationUpdateOne {
	if i != nil {
		ruo.SetPeriod(*i)
	}
	return ruo
}

// AddPeriod adds i to the "period" field.
func (ruo *RevocationUpdateOne) AddPeriod(i int) *RevocationUpdateOne {
	ruo.mutation.AddPeriod(i)
	return ruo
}

// Mutation returns the RevocationMutation object of the builder.
func (ruo *RevocationUpdateOne) Mutation() *RevocationMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RevocationUpdate builder.
func (ruo *RevocationUpdateOne) Where(ps ...predicate.Revocation) *RevocationUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RevocationUpdateOne) Select(field string, fields ...string) *RevocationUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Revocation entity.
func (ruo *RevocationUpdateOne) Save(ctx context.Context) (*Revocation, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RevocationUpdateOne) SaveX(ctx context.Context) *Revocation {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RevocationUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RevocationUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RevocationUpdateOne) sqlSave(ctx context.Context) (_node *Revocation, err error) {
	_spec := sqlgraph.NewUpdateSpec(revocation.Table, revocation.Columns, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Revocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, revocation.FieldID)
		for _, f := range fields {
			if !revocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != revocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Proof(); ok {
		_spec.SetField(revocation.FieldProof, field.TypeBytes, value)
	}
	if value, ok := ruo.mutation.Nym(); ok {
		_spec.SetField(revocation.FieldNym, field.TypeBytes, value)
	}
	if value, ok := ruo.mutation.Sigma(); ok {
		_spec.SetField(revocation.FieldSigma, field.TypeBytes, value)
	}
	if value, ok := ruo.mutation.Message(); ok {
		_spec.SetField(revocation.FieldMessage, field.TypeBytes, value)
	}
	if value, ok := ruo.mutation.Count(); ok {
		_spec.SetField(revocation.FieldCount, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedCount(); ok {
		_spec.AddField(revocation.FieldCount, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.Period(); ok {
		_spec.SetField(revocation.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedPeriod(); ok {
		_spec.AddField(revocation.FieldPeriod, field.TypeInt, value)
	}
	_node = &Revocation{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
