// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
	"github.com/akakou/zk-ban-system/core/gm/ent/revocation"
)

// RevocationUpdate is the builder for updating Revocation entities.
type RevocationUpdate struct {
	config
	hooks    []Hook
	mutation *RevocationMutation
}

// Where appends a list predicates to the RevocationUpdate builder.
func (ru *RevocationUpdate) Where(ps ...predicate.Revocation) *RevocationUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetNym sets the "nym" field.
func (ru *RevocationUpdate) SetNym(b []byte) *RevocationUpdate {
	ru.mutation.SetNym(b)
	return ru
}

// SetRevokedPeriod sets the "revoked_period" field.
func (ru *RevocationUpdate) SetRevokedPeriod(i int) *RevocationUpdate {
	ru.mutation.ResetRevokedPeriod()
	ru.mutation.SetRevokedPeriod(i)
	return ru
}

// SetNillableRevokedPeriod sets the "revoked_period" field if the given value is not nil.
func (ru *RevocationUpdate) SetNillableRevokedPeriod(i *int) *RevocationUpdate {
	if i != nil {
		ru.SetRevokedPeriod(*i)
	}
	return ru
}

// AddRevokedPeriod adds i to the "revoked_period" field.
func (ru *RevocationUpdate) AddRevokedPeriod(i int) *RevocationUpdate {
	ru.mutation.AddRevokedPeriod(i)
	return ru
}

// SetSignedPeriod sets the "signed_period" field.
func (ru *RevocationUpdate) SetSignedPeriod(i int) *RevocationUpdate {
	ru.mutation.ResetSignedPeriod()
	ru.mutation.SetSignedPeriod(i)
	return ru
}

// SetNillableSignedPeriod sets the "signed_period" field if the given value is not nil.
func (ru *RevocationUpdate) SetNillableSignedPeriod(i *int) *RevocationUpdate {
	if i != nil {
		ru.SetSignedPeriod(*i)
	}
	return ru
}

// AddSignedPeriod adds i to the "signed_period" field.
func (ru *RevocationUpdate) AddSignedPeriod(i int) *RevocationUpdate {
	ru.mutation.AddSignedPeriod(i)
	return ru
}

// Mutation returns the RevocationMutation object of the builder.
func (ru *RevocationUpdate) Mutation() *RevocationMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RevocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RevocationUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RevocationUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RevocationUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RevocationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(revocation.Table, revocation.Columns, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Nym(); ok {
		_spec.SetField(revocation.FieldNym, field.TypeBytes, value)
	}
	if value, ok := ru.mutation.RevokedPeriod(); ok {
		_spec.SetField(revocation.FieldRevokedPeriod, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedRevokedPeriod(); ok {
		_spec.AddField(revocation.FieldRevokedPeriod, field.TypeInt, value)
	}
	if value, ok := ru.mutation.SignedPeriod(); ok {
		_spec.SetField(revocation.FieldSignedPeriod, field.TypeInt, value)
	}
	if value, ok := ru.mutation.AddedSignedPeriod(); ok {
		_spec.AddField(revocation.FieldSignedPeriod, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RevocationUpdateOne is the builder for updating a single Revocation entity.
type RevocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RevocationMutation
}

// SetNym sets the "nym" field.
func (ruo *RevocationUpdateOne) SetNym(b []byte) *RevocationUpdateOne {
	ruo.mutation.SetNym(b)
	return ruo
}

// SetRevokedPeriod sets the "revoked_period" field.
func (ruo *RevocationUpdateOne) SetRevokedPeriod(i int) *RevocationUpdateOne {
	ruo.mutation.ResetRevokedPeriod()
	ruo.mutation.SetRevokedPeriod(i)
	return ruo
}

// SetNillableRevokedPeriod sets the "revoked_period" field if the given value is not nil.
func (ruo *RevocationUpdateOne) SetNillableRevokedPeriod(i *int) *RevocationUpdateOne {
	if i != nil {
		ruo.SetRevokedPeriod(*i)
	}
	return ruo
}

// AddRevokedPeriod adds i to the "revoked_period" field.
func (ruo *RevocationUpdateOne) AddRevokedPeriod(i int) *RevocationUpdateOne {
	ruo.mutation.AddRevokedPeriod(i)
	return ruo
}

// SetSignedPeriod sets the "signed_period" field.
func (ruo *RevocationUpdateOne) SetSignedPeriod(i int) *RevocationUpdateOne {
	ruo.mutation.ResetSignedPeriod()
	ruo.mutation.SetSignedPeriod(i)
	return ruo
}

// SetNillableSignedPeriod sets the "signed_period" field if the given value is not nil.
func (ruo *RevocationUpdateOne) SetNillableSignedPeriod(i *int) *RevocationUpdateOne {
	if i != nil {
		ruo.SetSignedPeriod(*i)
	}
	return ruo
}

// AddSignedPeriod adds i to the "signed_period" field.
func (ruo *RevocationUpdateOne) AddSignedPeriod(i int) *RevocationUpdateOne {
	ruo.mutation.AddSignedPeriod(i)
	return ruo
}

// Mutation returns the RevocationMutation object of the builder.
func (ruo *RevocationUpdateOne) Mutation() *RevocationMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RevocationUpdate builder.
func (ruo *RevocationUpdateOne) Where(ps ...predicate.Revocation) *RevocationUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RevocationUpdateOne) Select(field string, fields ...string) *RevocationUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Revocation entity.
func (ruo *RevocationUpdateOne) Save(ctx context.Context) (*Revocation, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RevocationUpdateOne) SaveX(ctx context.Context) *Revocation {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RevocationUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RevocationUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RevocationUpdateOne) sqlSave(ctx context.Context) (_node *Revocation, err error) {
	_spec := sqlgraph.NewUpdateSpec(revocation.Table, revocation.Columns, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Revocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, revocation.FieldID)
		for _, f := range fields {
			if !revocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != revocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Nym(); ok {
		_spec.SetField(revocation.FieldNym, field.TypeBytes, value)
	}
	if value, ok := ruo.mutation.RevokedPeriod(); ok {
		_spec.SetField(revocation.FieldRevokedPeriod, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedRevokedPeriod(); ok {
		_spec.AddField(revocation.FieldRevokedPeriod, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.SignedPeriod(); ok {
		_spec.SetField(revocation.FieldSignedPeriod, field.TypeInt, value)
	}
	if value, ok := ruo.mutation.AddedSignedPeriod(); ok {
		_spec.AddField(revocation.FieldSignedPeriod, field.TypeInt, value)
	}
	_node = &Revocation{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
