// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/revocation"
)

// RevocationCreate is the builder for creating a Revocation entity.
type RevocationCreate struct {
	config
	mutation *RevocationMutation
	hooks    []Hook
}

// SetProof sets the "proof" field.
func (rc *RevocationCreate) SetProof(b []byte) *RevocationCreate {
	rc.mutation.SetProof(b)
	return rc
}

// SetNym sets the "nym" field.
func (rc *RevocationCreate) SetNym(b []byte) *RevocationCreate {
	rc.mutation.SetNym(b)
	return rc
}

// SetSigma sets the "sigma" field.
func (rc *RevocationCreate) SetSigma(b []byte) *RevocationCreate {
	rc.mutation.SetSigma(b)
	return rc
}

// SetMessage sets the "message" field.
func (rc *RevocationCreate) SetMessage(b []byte) *RevocationCreate {
	rc.mutation.SetMessage(b)
	return rc
}

// SetCount sets the "count" field.
func (rc *RevocationCreate) SetCount(i int) *RevocationCreate {
	rc.mutation.SetCount(i)
	return rc
}

// SetPeriod sets the "period" field.
func (rc *RevocationCreate) SetPeriod(i int) *RevocationCreate {
	rc.mutation.SetPeriod(i)
	return rc
}

// Mutation returns the RevocationMutation object of the builder.
func (rc *RevocationCreate) Mutation() *RevocationMutation {
	return rc.mutation
}

// Save creates the Revocation in the database.
func (rc *RevocationCreate) Save(ctx context.Context) (*Revocation, error) {
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RevocationCreate) SaveX(ctx context.Context) *Revocation {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RevocationCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RevocationCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RevocationCreate) check() error {
	if _, ok := rc.mutation.Proof(); !ok {
		return &ValidationError{Name: "proof", err: errors.New(`ent: missing required field "Revocation.proof"`)}
	}
	if _, ok := rc.mutation.Nym(); !ok {
		return &ValidationError{Name: "nym", err: errors.New(`ent: missing required field "Revocation.nym"`)}
	}
	if _, ok := rc.mutation.Sigma(); !ok {
		return &ValidationError{Name: "sigma", err: errors.New(`ent: missing required field "Revocation.sigma"`)}
	}
	if _, ok := rc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Revocation.message"`)}
	}
	if _, ok := rc.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Revocation.count"`)}
	}
	if _, ok := rc.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "Revocation.period"`)}
	}
	return nil
}

func (rc *RevocationCreate) sqlSave(ctx context.Context) (*Revocation, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RevocationCreate) createSpec() (*Revocation, *sqlgraph.CreateSpec) {
	var (
		_node = &Revocation{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(revocation.Table, sqlgraph.NewFieldSpec(revocation.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.Proof(); ok {
		_spec.SetField(revocation.FieldProof, field.TypeBytes, value)
		_node.Proof = value
	}
	if value, ok := rc.mutation.Nym(); ok {
		_spec.SetField(revocation.FieldNym, field.TypeBytes, value)
		_node.Nym = value
	}
	if value, ok := rc.mutation.Sigma(); ok {
		_spec.SetField(revocation.FieldSigma, field.TypeBytes, value)
		_node.Sigma = value
	}
	if value, ok := rc.mutation.Message(); ok {
		_spec.SetField(revocation.FieldMessage, field.TypeBytes, value)
		_node.Message = value
	}
	if value, ok := rc.mutation.Count(); ok {
		_spec.SetField(revocation.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := rc.mutation.Period(); ok {
		_spec.SetField(revocation.FieldPeriod, field.TypeInt, value)
		_node.Period = value
	}
	return _node, _spec
}

// RevocationCreateBulk is the builder for creating many Revocation entities in bulk.
type RevocationCreateBulk struct {
	config
	err      error
	builders []*RevocationCreate
}

// Save creates the Revocation entities in the database.
func (rcb *RevocationCreateBulk) Save(ctx context.Context) ([]*Revocation, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Revocation, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RevocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RevocationCreateBulk) SaveX(ctx context.Context) []*Revocation {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RevocationCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RevocationCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
