// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/credential"
	"github.com/akakou/zk-ban-system/core/gm/ent/updateticket"
)

// UpdateTicketCreate is the builder for creating a UpdateTicket entity.
type UpdateTicketCreate struct {
	config
	mutation *UpdateTicketMutation
	hooks    []Hook
}

// SetTicket sets the "ticket" field.
func (utc *UpdateTicketCreate) SetTicket(b []byte) *UpdateTicketCreate {
	utc.mutation.SetTicket(b)
	return utc
}

// AddCredentialIDs adds the "credential" edge to the Credential entity by IDs.
func (utc *UpdateTicketCreate) AddCredentialIDs(ids ...int) *UpdateTicketCreate {
	utc.mutation.AddCredentialIDs(ids...)
	return utc
}

// AddCredential adds the "credential" edges to the Credential entity.
func (utc *UpdateTicketCreate) AddCredential(c ...*Credential) *UpdateTicketCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return utc.AddCredentialIDs(ids...)
}

// Mutation returns the UpdateTicketMutation object of the builder.
func (utc *UpdateTicketCreate) Mutation() *UpdateTicketMutation {
	return utc.mutation
}

// Save creates the UpdateTicket in the database.
func (utc *UpdateTicketCreate) Save(ctx context.Context) (*UpdateTicket, error) {
	return withHooks(ctx, utc.sqlSave, utc.mutation, utc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (utc *UpdateTicketCreate) SaveX(ctx context.Context) *UpdateTicket {
	v, err := utc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (utc *UpdateTicketCreate) Exec(ctx context.Context) error {
	_, err := utc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utc *UpdateTicketCreate) ExecX(ctx context.Context) {
	if err := utc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (utc *UpdateTicketCreate) check() error {
	if _, ok := utc.mutation.Ticket(); !ok {
		return &ValidationError{Name: "ticket", err: errors.New(`ent: missing required field "UpdateTicket.ticket"`)}
	}
	return nil
}

func (utc *UpdateTicketCreate) sqlSave(ctx context.Context) (*UpdateTicket, error) {
	if err := utc.check(); err != nil {
		return nil, err
	}
	_node, _spec := utc.createSpec()
	if err := sqlgraph.CreateNode(ctx, utc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	utc.mutation.id = &_node.ID
	utc.mutation.done = true
	return _node, nil
}

func (utc *UpdateTicketCreate) createSpec() (*UpdateTicket, *sqlgraph.CreateSpec) {
	var (
		_node = &UpdateTicket{config: utc.config}
		_spec = sqlgraph.NewCreateSpec(updateticket.Table, sqlgraph.NewFieldSpec(updateticket.FieldID, field.TypeInt))
	)
	if value, ok := utc.mutation.Ticket(); ok {
		_spec.SetField(updateticket.FieldTicket, field.TypeBytes, value)
		_node.Ticket = value
	}
	if nodes := utc.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UpdateTicketCreateBulk is the builder for creating many UpdateTicket entities in bulk.
type UpdateTicketCreateBulk struct {
	config
	err      error
	builders []*UpdateTicketCreate
}

// Save creates the UpdateTicket entities in the database.
func (utcb *UpdateTicketCreateBulk) Save(ctx context.Context) ([]*UpdateTicket, error) {
	if utcb.err != nil {
		return nil, utcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(utcb.builders))
	nodes := make([]*UpdateTicket, len(utcb.builders))
	mutators := make([]Mutator, len(utcb.builders))
	for i := range utcb.builders {
		func(i int, root context.Context) {
			builder := utcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpdateTicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, utcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, utcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, utcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (utcb *UpdateTicketCreateBulk) SaveX(ctx context.Context) []*UpdateTicket {
	v, err := utcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (utcb *UpdateTicketCreateBulk) Exec(ctx context.Context) error {
	_, err := utcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utcb *UpdateTicketCreateBulk) ExecX(ctx context.Context) {
	if err := utcb.Exec(ctx); err != nil {
		panic(err)
	}
}
