// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
	"github.com/akakou/zk-ban-system/core/gm/ent/updateticket"
)

// UpdateTicketDelete is the builder for deleting a UpdateTicket entity.
type UpdateTicketDelete struct {
	config
	hooks    []Hook
	mutation *UpdateTicketMutation
}

// Where appends a list predicates to the UpdateTicketDelete builder.
func (utd *UpdateTicketDelete) Where(ps ...predicate.UpdateTicket) *UpdateTicketDelete {
	utd.mutation.Where(ps...)
	return utd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (utd *UpdateTicketDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, utd.sqlExec, utd.mutation, utd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (utd *UpdateTicketDelete) ExecX(ctx context.Context) int {
	n, err := utd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (utd *UpdateTicketDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(updateticket.Table, sqlgraph.NewFieldSpec(updateticket.FieldID, field.TypeInt))
	if ps := utd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, utd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	utd.mutation.done = true
	return affected, err
}

// UpdateTicketDeleteOne is the builder for deleting a single UpdateTicket entity.
type UpdateTicketDeleteOne struct {
	utd *UpdateTicketDelete
}

// Where appends a list predicates to the UpdateTicketDelete builder.
func (utdo *UpdateTicketDeleteOne) Where(ps ...predicate.UpdateTicket) *UpdateTicketDeleteOne {
	utdo.utd.mutation.Where(ps...)
	return utdo
}

// Exec executes the deletion query.
func (utdo *UpdateTicketDeleteOne) Exec(ctx context.Context) error {
	n, err := utdo.utd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{updateticket.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (utdo *UpdateTicketDeleteOne) ExecX(ctx context.Context) {
	if err := utdo.Exec(ctx); err != nil {
		panic(err)
	}
}
