// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/gm/ent/credential"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
	"github.com/akakou/zk-ban-system/core/gm/ent/updateticket"
)

// UpdateTicketUpdate is the builder for updating UpdateTicket entities.
type UpdateTicketUpdate struct {
	config
	hooks    []Hook
	mutation *UpdateTicketMutation
}

// Where appends a list predicates to the UpdateTicketUpdate builder.
func (utu *UpdateTicketUpdate) Where(ps ...predicate.UpdateTicket) *UpdateTicketUpdate {
	utu.mutation.Where(ps...)
	return utu
}

// SetTicket sets the "ticket" field.
func (utu *UpdateTicketUpdate) SetTicket(b []byte) *UpdateTicketUpdate {
	utu.mutation.SetTicket(b)
	return utu
}

// AddCredentialIDs adds the "credential" edge to the Credential entity by IDs.
func (utu *UpdateTicketUpdate) AddCredentialIDs(ids ...int) *UpdateTicketUpdate {
	utu.mutation.AddCredentialIDs(ids...)
	return utu
}

// AddCredential adds the "credential" edges to the Credential entity.
func (utu *UpdateTicketUpdate) AddCredential(c ...*Credential) *UpdateTicketUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return utu.AddCredentialIDs(ids...)
}

// Mutation returns the UpdateTicketMutation object of the builder.
func (utu *UpdateTicketUpdate) Mutation() *UpdateTicketMutation {
	return utu.mutation
}

// ClearCredential clears all "credential" edges to the Credential entity.
func (utu *UpdateTicketUpdate) ClearCredential() *UpdateTicketUpdate {
	utu.mutation.ClearCredential()
	return utu
}

// RemoveCredentialIDs removes the "credential" edge to Credential entities by IDs.
func (utu *UpdateTicketUpdate) RemoveCredentialIDs(ids ...int) *UpdateTicketUpdate {
	utu.mutation.RemoveCredentialIDs(ids...)
	return utu
}

// RemoveCredential removes "credential" edges to Credential entities.
func (utu *UpdateTicketUpdate) RemoveCredential(c ...*Credential) *UpdateTicketUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return utu.RemoveCredentialIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (utu *UpdateTicketUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, utu.sqlSave, utu.mutation, utu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (utu *UpdateTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := utu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (utu *UpdateTicketUpdate) Exec(ctx context.Context) error {
	_, err := utu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utu *UpdateTicketUpdate) ExecX(ctx context.Context) {
	if err := utu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (utu *UpdateTicketUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(updateticket.Table, updateticket.Columns, sqlgraph.NewFieldSpec(updateticket.FieldID, field.TypeInt))
	if ps := utu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := utu.mutation.Ticket(); ok {
		_spec.SetField(updateticket.FieldTicket, field.TypeBytes, value)
	}
	if utu.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utu.mutation.RemovedCredentialIDs(); len(nodes) > 0 && !utu.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utu.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, utu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{updateticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	utu.mutation.done = true
	return n, nil
}

// UpdateTicketUpdateOne is the builder for updating a single UpdateTicket entity.
type UpdateTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpdateTicketMutation
}

// SetTicket sets the "ticket" field.
func (utuo *UpdateTicketUpdateOne) SetTicket(b []byte) *UpdateTicketUpdateOne {
	utuo.mutation.SetTicket(b)
	return utuo
}

// AddCredentialIDs adds the "credential" edge to the Credential entity by IDs.
func (utuo *UpdateTicketUpdateOne) AddCredentialIDs(ids ...int) *UpdateTicketUpdateOne {
	utuo.mutation.AddCredentialIDs(ids...)
	return utuo
}

// AddCredential adds the "credential" edges to the Credential entity.
func (utuo *UpdateTicketUpdateOne) AddCredential(c ...*Credential) *UpdateTicketUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return utuo.AddCredentialIDs(ids...)
}

// Mutation returns the UpdateTicketMutation object of the builder.
func (utuo *UpdateTicketUpdateOne) Mutation() *UpdateTicketMutation {
	return utuo.mutation
}

// ClearCredential clears all "credential" edges to the Credential entity.
func (utuo *UpdateTicketUpdateOne) ClearCredential() *UpdateTicketUpdateOne {
	utuo.mutation.ClearCredential()
	return utuo
}

// RemoveCredentialIDs removes the "credential" edge to Credential entities by IDs.
func (utuo *UpdateTicketUpdateOne) RemoveCredentialIDs(ids ...int) *UpdateTicketUpdateOne {
	utuo.mutation.RemoveCredentialIDs(ids...)
	return utuo
}

// RemoveCredential removes "credential" edges to Credential entities.
func (utuo *UpdateTicketUpdateOne) RemoveCredential(c ...*Credential) *UpdateTicketUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return utuo.RemoveCredentialIDs(ids...)
}

// Where appends a list predicates to the UpdateTicketUpdate builder.
func (utuo *UpdateTicketUpdateOne) Where(ps ...predicate.UpdateTicket) *UpdateTicketUpdateOne {
	utuo.mutation.Where(ps...)
	return utuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (utuo *UpdateTicketUpdateOne) Select(field string, fields ...string) *UpdateTicketUpdateOne {
	utuo.fields = append([]string{field}, fields...)
	return utuo
}

// Save executes the query and returns the updated UpdateTicket entity.
func (utuo *UpdateTicketUpdateOne) Save(ctx context.Context) (*UpdateTicket, error) {
	return withHooks(ctx, utuo.sqlSave, utuo.mutation, utuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (utuo *UpdateTicketUpdateOne) SaveX(ctx context.Context) *UpdateTicket {
	node, err := utuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (utuo *UpdateTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := utuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (utuo *UpdateTicketUpdateOne) ExecX(ctx context.Context) {
	if err := utuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (utuo *UpdateTicketUpdateOne) sqlSave(ctx context.Context) (_node *UpdateTicket, err error) {
	_spec := sqlgraph.NewUpdateSpec(updateticket.Table, updateticket.Columns, sqlgraph.NewFieldSpec(updateticket.FieldID, field.TypeInt))
	id, ok := utuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpdateTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := utuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, updateticket.FieldID)
		for _, f := range fields {
			if !updateticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != updateticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := utuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := utuo.mutation.Ticket(); ok {
		_spec.SetField(updateticket.FieldTicket, field.TypeBytes, value)
	}
	if utuo.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utuo.mutation.RemovedCredentialIDs(); len(nodes) > 0 && !utuo.mutation.CredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := utuo.mutation.CredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   updateticket.CredentialTable,
			Columns: []string{updateticket.CredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpdateTicket{config: utuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, utuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{updateticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	utuo.mutation.done = true
	return _node, nil
}
