// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/gm/ent/updateticket"
)

// UpdateTicket is the model entity for the UpdateTicket schema.
type UpdateTicket struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ticket holds the value of the "ticket" field.
	Ticket       []byte `json:"ticket,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpdateTicket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case updateticket.FieldTicket:
			values[i] = new([]byte)
		case updateticket.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpdateTicket fields.
func (ut *UpdateTicket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case updateticket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ut.ID = int(value.Int64)
		case updateticket.FieldTicket:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ticket", values[i])
			} else if value != nil {
				ut.Ticket = *value
			}
		default:
			ut.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpdateTicket.
// This includes values selected through modifiers, order, etc.
func (ut *UpdateTicket) Value(name string) (ent.Value, error) {
	return ut.selectValues.Get(name)
}

// Update returns a builder for updating this UpdateTicket.
// Note that you need to call UpdateTicket.Unwrap() before calling this method if this UpdateTicket
// was returned from a transaction, and the transaction was committed or rolled back.
func (ut *UpdateTicket) Update() *UpdateTicketUpdateOne {
	return NewUpdateTicketClient(ut.config).UpdateOne(ut)
}

// Unwrap unwraps the UpdateTicket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ut *UpdateTicket) Unwrap() *UpdateTicket {
	_tx, ok := ut.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpdateTicket is not a transactional entity")
	}
	ut.config.driver = _tx.drv
	return ut
}

// String implements the fmt.Stringer.
func (ut *UpdateTicket) String() string {
	var builder strings.Builder
	builder.WriteString("UpdateTicket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ut.ID))
	builder.WriteString("ticket=")
	builder.WriteString(fmt.Sprintf("%v", ut.Ticket))
	builder.WriteByte(')')
	return builder.String()
}

// UpdateTickets is a parsable slice of UpdateTicket.
type UpdateTickets []*UpdateTicket
