// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IDTokensColumns holds the columns for the "id_tokens" table.
	IDTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "id_token", Type: field.TypeString},
	}
	// IDTokensTable holds the schema information for the "id_tokens" table.
	IDTokensTable = &schema.Table{
		Name:       "id_tokens",
		Columns:    IDTokensColumns,
		PrimaryKey: []*schema.Column{IDTokensColumns[0]},
	}
	// RevocationsColumns holds the columns for the "revocations" table.
	RevocationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nym", Type: field.TypeBytes},
		{Name: "count", Type: field.TypeInt},
		{Name: "revoked_period", Type: field.TypeInt},
		{Name: "signed_period", Type: field.TypeInt},
	}
	// RevocationsTable holds the schema information for the "revocations" table.
	RevocationsTable = &schema.Table{
		Name:       "revocations",
		Columns:    RevocationsColumns,
		PrimaryKey: []*schema.Column{RevocationsColumns[0]},
	}
	// UpdateTicketsColumns holds the columns for the "update_tickets" table.
	UpdateTicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ticket", Type: field.TypeBytes},
	}
	// UpdateTicketsTable holds the schema information for the "update_tickets" table.
	UpdateTicketsTable = &schema.Table{
		Name:       "update_tickets",
		Columns:    UpdateTicketsColumns,
		PrimaryKey: []*schema.Column{UpdateTicketsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IDTokensTable,
		RevocationsTable,
		UpdateTicketsTable,
	}
)

func init() {
}
