// Code generated by ent, DO NOT EDIT.

package pseudonyms

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pseudonyms type in the database.
	Label = "pseudonyms"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNym holds the string denoting the nym field in the database.
	FieldNym = "nym"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// Table holds the table name of the pseudonyms in the database.
	Table = "pseudonyms"
)

// Columns holds all SQL columns for pseudonyms fields.
var Columns = []string{
	FieldID,
	FieldNym,
	FieldCount,
	FieldPeriod,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Pseudonyms queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}
