// Code generated by ent, DO NOT EDIT.

package pseudonyms

import (
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/verifier/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLTE(FieldID, id))
}

// Nym applies equality check predicate on the "nym" field. It's identical to NymEQ.
func Nym(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldNym, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldCount, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldPeriod, v))
}

// NymEQ applies the EQ predicate on the "nym" field.
func NymEQ(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldNym, v))
}

// NymNEQ applies the NEQ predicate on the "nym" field.
func NymNEQ(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNEQ(FieldNym, v))
}

// NymIn applies the In predicate on the "nym" field.
func NymIn(vs ...[]byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldIn(FieldNym, vs...))
}

// NymNotIn applies the NotIn predicate on the "nym" field.
func NymNotIn(vs ...[]byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNotIn(FieldNym, vs...))
}

// NymGT applies the GT predicate on the "nym" field.
func NymGT(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGT(FieldNym, v))
}

// NymGTE applies the GTE predicate on the "nym" field.
func NymGTE(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGTE(FieldNym, v))
}

// NymLT applies the LT predicate on the "nym" field.
func NymLT(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLT(FieldNym, v))
}

// NymLTE applies the LTE predicate on the "nym" field.
func NymLTE(v []byte) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLTE(FieldNym, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLTE(FieldCount, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v int) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.FieldLTE(FieldPeriod, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pseudonyms) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pseudonyms) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pseudonyms) predicate.Pseudonyms {
	return predicate.Pseudonyms(sql.NotPredicates(p))
}
