// Code generated by ent, DO NOT EDIT.

package credential

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the credential type in the database.
	Label = "credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCredential holds the string denoting the credential field in the database.
	FieldCredential = "credential"
	// EdgeUpdateTicket holds the string denoting the updateticket edge name in mutations.
	EdgeUpdateTicket = "updateTicket"
	// Table holds the table name of the credential in the database.
	Table = "credentials"
	// UpdateTicketTable is the table that holds the updateTicket relation/edge.
	UpdateTicketTable = "credentials"
	// UpdateTicketInverseTable is the table name for the UpdateTicket entity.
	// It exists in this package in order to avoid circular dependency with the "updateticket" package.
	UpdateTicketInverseTable = "update_tickets"
	// UpdateTicketColumn is the table column denoting the updateTicket relation/edge.
	UpdateTicketColumn = "update_ticket_credential"
)

// Columns holds all SQL columns for credential fields.
var Columns = []string{
	FieldID,
	FieldCredential,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "credentials"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"update_ticket_credential",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Credential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpdateTicketField orders the results by updateTicket field.
func ByUpdateTicketField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpdateTicketStep(), sql.OrderByField(field, opts...))
	}
}
func newUpdateTicketStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpdateTicketInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UpdateTicketTable, UpdateTicketColumn),
	)
}
