// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PseudonymsColumns holds the columns for the "pseudonyms" table.
	PseudonymsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nym", Type: field.TypeBytes},
		{Name: "count", Type: field.TypeInt},
		{Name: "period", Type: field.TypeInt},
	}
	// PseudonymsTable holds the schema information for the "pseudonyms" table.
	PseudonymsTable = &schema.Table{
		Name:       "pseudonyms",
		Columns:    PseudonymsColumns,
		PrimaryKey: []*schema.Column{PseudonymsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PseudonymsTable,
	}
)

func init() {
}
