// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/akakou/zk-ban-system/core/verifier/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/verifier/ent/pseudonyms"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Pseudonyms is the client for interacting with the Pseudonyms builders.
	Pseudonyms *PseudonymsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Pseudonyms = NewPseudonymsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Pseudonyms: NewPseudonymsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Pseudonyms: NewPseudonymsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Pseudonyms.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Pseudonyms.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Pseudonyms.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *PseudonymsMutation:
		return c.Pseudonyms.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// PseudonymsClient is a client for the Pseudonyms schema.
type PseudonymsClient struct {
	config
}

// NewPseudonymsClient returns a client for the Pseudonyms from the given config.
func NewPseudonymsClient(c config) *PseudonymsClient {
	return &PseudonymsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pseudonyms.Hooks(f(g(h())))`.
func (c *PseudonymsClient) Use(hooks ...Hook) {
	c.hooks.Pseudonyms = append(c.hooks.Pseudonyms, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pseudonyms.Intercept(f(g(h())))`.
func (c *PseudonymsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pseudonyms = append(c.inters.Pseudonyms, interceptors...)
}

// Create returns a builder for creating a Pseudonyms entity.
func (c *PseudonymsClient) Create() *PseudonymsCreate {
	mutation := newPseudonymsMutation(c.config, OpCreate)
	return &PseudonymsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pseudonyms entities.
func (c *PseudonymsClient) CreateBulk(builders ...*PseudonymsCreate) *PseudonymsCreateBulk {
	return &PseudonymsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PseudonymsClient) MapCreateBulk(slice any, setFunc func(*PseudonymsCreate, int)) *PseudonymsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PseudonymsCreateBulk{err: fmt.Errorf("calling to PseudonymsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PseudonymsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PseudonymsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pseudonyms.
func (c *PseudonymsClient) Update() *PseudonymsUpdate {
	mutation := newPseudonymsMutation(c.config, OpUpdate)
	return &PseudonymsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PseudonymsClient) UpdateOne(ps *Pseudonyms) *PseudonymsUpdateOne {
	mutation := newPseudonymsMutation(c.config, OpUpdateOne, withPseudonyms(ps))
	return &PseudonymsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PseudonymsClient) UpdateOneID(id int) *PseudonymsUpdateOne {
	mutation := newPseudonymsMutation(c.config, OpUpdateOne, withPseudonymsID(id))
	return &PseudonymsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pseudonyms.
func (c *PseudonymsClient) Delete() *PseudonymsDelete {
	mutation := newPseudonymsMutation(c.config, OpDelete)
	return &PseudonymsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PseudonymsClient) DeleteOne(ps *Pseudonyms) *PseudonymsDeleteOne {
	return c.DeleteOneID(ps.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PseudonymsClient) DeleteOneID(id int) *PseudonymsDeleteOne {
	builder := c.Delete().Where(pseudonyms.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PseudonymsDeleteOne{builder}
}

// Query returns a query builder for Pseudonyms.
func (c *PseudonymsClient) Query() *PseudonymsQuery {
	return &PseudonymsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePseudonyms},
		inters: c.Interceptors(),
	}
}

// Get returns a Pseudonyms entity by its id.
func (c *PseudonymsClient) Get(ctx context.Context, id int) (*Pseudonyms, error) {
	return c.Query().Where(pseudonyms.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PseudonymsClient) GetX(ctx context.Context, id int) *Pseudonyms {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PseudonymsClient) Hooks() []Hook {
	return c.hooks.Pseudonyms
}

// Interceptors returns the client interceptors.
func (c *PseudonymsClient) Interceptors() []Interceptor {
	return c.inters.Pseudonyms
}

func (c *PseudonymsClient) mutate(ctx context.Context, m *PseudonymsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PseudonymsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PseudonymsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PseudonymsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PseudonymsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pseudonyms mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Pseudonyms []ent.Hook
	}
	inters struct {
		Pseudonyms []ent.Interceptor
	}
)
