// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/verifier/ent/predicate"
	"github.com/akakou/zk-ban-system/core/verifier/ent/pseudonyms"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePseudonyms = "Pseudonyms"
)

// PseudonymsMutation represents an operation that mutates the Pseudonyms nodes in the graph.
type PseudonymsMutation struct {
	config
	op            Op
	typ           string
	id            *int
	nym           *[]byte
	count         *int
	addcount      *int
	period        *int
	addperiod     *int
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Pseudonyms, error)
	predicates    []predicate.Pseudonyms
}

var _ ent.Mutation = (*PseudonymsMutation)(nil)

// pseudonymsOption allows management of the mutation configuration using functional options.
type pseudonymsOption func(*PseudonymsMutation)

// newPseudonymsMutation creates new mutation for the Pseudonyms entity.
func newPseudonymsMutation(c config, op Op, opts ...pseudonymsOption) *PseudonymsMutation {
	m := &PseudonymsMutation{
		config:        c,
		op:            op,
		typ:           TypePseudonyms,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPseudonymsID sets the ID field of the mutation.
func withPseudonymsID(id int) pseudonymsOption {
	return func(m *PseudonymsMutation) {
		var (
			err   error
			once  sync.Once
			value *Pseudonyms
		)
		m.oldValue = func(ctx context.Context) (*Pseudonyms, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Pseudonyms.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPseudonyms sets the old Pseudonyms of the mutation.
func withPseudonyms(node *Pseudonyms) pseudonymsOption {
	return func(m *PseudonymsMutation) {
		m.oldValue = func(context.Context) (*Pseudonyms, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PseudonymsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PseudonymsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PseudonymsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PseudonymsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Pseudonyms.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNym sets the "nym" field.
func (m *PseudonymsMutation) SetNym(b []byte) {
	m.nym = &b
}

// Nym returns the value of the "nym" field in the mutation.
func (m *PseudonymsMutation) Nym() (r []byte, exists bool) {
	v := m.nym
	if v == nil {
		return
	}
	return *v, true
}

// OldNym returns the old "nym" field's value of the Pseudonyms entity.
// If the Pseudonyms object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PseudonymsMutation) OldNym(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNym is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNym requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNym: %w", err)
	}
	return oldValue.Nym, nil
}

// ResetNym resets all changes to the "nym" field.
func (m *PseudonymsMutation) ResetNym() {
	m.nym = nil
}

// SetCount sets the "count" field.
func (m *PseudonymsMutation) SetCount(i int) {
	m.count = &i
	m.addcount = nil
}

// Count returns the value of the "count" field in the mutation.
func (m *PseudonymsMutation) Count() (r int, exists bool) {
	v := m.count
	if v == nil {
		return
	}
	return *v, true
}

// OldCount returns the old "count" field's value of the Pseudonyms entity.
// If the Pseudonyms object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PseudonymsMutation) OldCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCount: %w", err)
	}
	return oldValue.Count, nil
}

// AddCount adds i to the "count" field.
func (m *PseudonymsMutation) AddCount(i int) {
	if m.addcount != nil {
		*m.addcount += i
	} else {
		m.addcount = &i
	}
}

// AddedCount returns the value that was added to the "count" field in this mutation.
func (m *PseudonymsMutation) AddedCount() (r int, exists bool) {
	v := m.addcount
	if v == nil {
		return
	}
	return *v, true
}

// ResetCount resets all changes to the "count" field.
func (m *PseudonymsMutation) ResetCount() {
	m.count = nil
	m.addcount = nil
}

// SetPeriod sets the "period" field.
func (m *PseudonymsMutation) SetPeriod(i int) {
	m.period = &i
	m.addperiod = nil
}

// Period returns the value of the "period" field in the mutation.
func (m *PseudonymsMutation) Period() (r int, exists bool) {
	v := m.period
	if v == nil {
		return
	}
	return *v, true
}

// OldPeriod returns the old "period" field's value of the Pseudonyms entity.
// If the Pseudonyms object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PseudonymsMutation) OldPeriod(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPeriod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPeriod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPeriod: %w", err)
	}
	return oldValue.Period, nil
}

// AddPeriod adds i to the "period" field.
func (m *PseudonymsMutation) AddPeriod(i int) {
	if m.addperiod != nil {
		*m.addperiod += i
	} else {
		m.addperiod = &i
	}
}

// AddedPeriod returns the value that was added to the "period" field in this mutation.
func (m *PseudonymsMutation) AddedPeriod() (r int, exists bool) {
	v := m.addperiod
	if v == nil {
		return
	}
	return *v, true
}

// ResetPeriod resets all changes to the "period" field.
func (m *PseudonymsMutation) ResetPeriod() {
	m.period = nil
	m.addperiod = nil
}

// Where appends a list predicates to the PseudonymsMutation builder.
func (m *PseudonymsMutation) Where(ps ...predicate.Pseudonyms) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PseudonymsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PseudonymsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Pseudonyms, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PseudonymsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PseudonymsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Pseudonyms).
func (m *PseudonymsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PseudonymsMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.nym != nil {
		fields = append(fields, pseudonyms.FieldNym)
	}
	if m.count != nil {
		fields = append(fields, pseudonyms.FieldCount)
	}
	if m.period != nil {
		fields = append(fields, pseudonyms.FieldPeriod)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PseudonymsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pseudonyms.FieldNym:
		return m.Nym()
	case pseudonyms.FieldCount:
		return m.Count()
	case pseudonyms.FieldPeriod:
		return m.Period()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PseudonymsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pseudonyms.FieldNym:
		return m.OldNym(ctx)
	case pseudonyms.FieldCount:
		return m.OldCount(ctx)
	case pseudonyms.FieldPeriod:
		return m.OldPeriod(ctx)
	}
	return nil, fmt.Errorf("unknown Pseudonyms field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PseudonymsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pseudonyms.FieldNym:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNym(v)
		return nil
	case pseudonyms.FieldCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCount(v)
		return nil
	case pseudonyms.FieldPeriod:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPeriod(v)
		return nil
	}
	return fmt.Errorf("unknown Pseudonyms field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PseudonymsMutation) AddedFields() []string {
	var fields []string
	if m.addcount != nil {
		fields = append(fields, pseudonyms.FieldCount)
	}
	if m.addperiod != nil {
		fields = append(fields, pseudonyms.FieldPeriod)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PseudonymsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pseudonyms.FieldCount:
		return m.AddedCount()
	case pseudonyms.FieldPeriod:
		return m.AddedPeriod()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PseudonymsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pseudonyms.FieldCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCount(v)
		return nil
	case pseudonyms.FieldPeriod:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPeriod(v)
		return nil
	}
	return fmt.Errorf("unknown Pseudonyms numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PseudonymsMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PseudonymsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PseudonymsMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Pseudonyms nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PseudonymsMutation) ResetField(name string) error {
	switch name {
	case pseudonyms.FieldNym:
		m.ResetNym()
		return nil
	case pseudonyms.FieldCount:
		m.ResetCount()
		return nil
	case pseudonyms.FieldPeriod:
		m.ResetPeriod()
		return nil
	}
	return fmt.Errorf("unknown Pseudonyms field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PseudonymsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PseudonymsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PseudonymsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PseudonymsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PseudonymsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PseudonymsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PseudonymsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Pseudonyms unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PseudonymsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Pseudonyms edge %s", name)
}
