// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/verifier/ent/predicate"
	"github.com/akakou/zk-ban-system/core/verifier/ent/pseudonyms"
)

// PseudonymsUpdate is the builder for updating Pseudonyms entities.
type PseudonymsUpdate struct {
	config
	hooks    []Hook
	mutation *PseudonymsMutation
}

// Where appends a list predicates to the PseudonymsUpdate builder.
func (pu *PseudonymsUpdate) Where(ps ...predicate.Pseudonyms) *PseudonymsUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetNym sets the "nym" field.
func (pu *PseudonymsUpdate) SetNym(b []byte) *PseudonymsUpdate {
	pu.mutation.SetNym(b)
	return pu
}

// SetCount sets the "count" field.
func (pu *PseudonymsUpdate) SetCount(i int) *PseudonymsUpdate {
	pu.mutation.ResetCount()
	pu.mutation.SetCount(i)
	return pu
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (pu *PseudonymsUpdate) SetNillableCount(i *int) *PseudonymsUpdate {
	if i != nil {
		pu.SetCount(*i)
	}
	return pu
}

// AddCount adds i to the "count" field.
func (pu *PseudonymsUpdate) AddCount(i int) *PseudonymsUpdate {
	pu.mutation.AddCount(i)
	return pu
}

// SetPeriod sets the "period" field.
func (pu *PseudonymsUpdate) SetPeriod(i int) *PseudonymsUpdate {
	pu.mutation.ResetPeriod()
	pu.mutation.SetPeriod(i)
	return pu
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (pu *PseudonymsUpdate) SetNillablePeriod(i *int) *PseudonymsUpdate {
	if i != nil {
		pu.SetPeriod(*i)
	}
	return pu
}

// AddPeriod adds i to the "period" field.
func (pu *PseudonymsUpdate) AddPeriod(i int) *PseudonymsUpdate {
	pu.mutation.AddPeriod(i)
	return pu
}

// Mutation returns the PseudonymsMutation object of the builder.
func (pu *PseudonymsUpdate) Mutation() *PseudonymsMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PseudonymsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PseudonymsUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PseudonymsUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PseudonymsUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PseudonymsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pseudonyms.Table, pseudonyms.Columns, sqlgraph.NewFieldSpec(pseudonyms.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Nym(); ok {
		_spec.SetField(pseudonyms.FieldNym, field.TypeBytes, value)
	}
	if value, ok := pu.mutation.Count(); ok {
		_spec.SetField(pseudonyms.FieldCount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedCount(); ok {
		_spec.AddField(pseudonyms.FieldCount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Period(); ok {
		_spec.SetField(pseudonyms.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedPeriod(); ok {
		_spec.AddField(pseudonyms.FieldPeriod, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pseudonyms.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PseudonymsUpdateOne is the builder for updating a single Pseudonyms entity.
type PseudonymsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PseudonymsMutation
}

// SetNym sets the "nym" field.
func (puo *PseudonymsUpdateOne) SetNym(b []byte) *PseudonymsUpdateOne {
	puo.mutation.SetNym(b)
	return puo
}

// SetCount sets the "count" field.
func (puo *PseudonymsUpdateOne) SetCount(i int) *PseudonymsUpdateOne {
	puo.mutation.ResetCount()
	puo.mutation.SetCount(i)
	return puo
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (puo *PseudonymsUpdateOne) SetNillableCount(i *int) *PseudonymsUpdateOne {
	if i != nil {
		puo.SetCount(*i)
	}
	return puo
}

// AddCount adds i to the "count" field.
func (puo *PseudonymsUpdateOne) AddCount(i int) *PseudonymsUpdateOne {
	puo.mutation.AddCount(i)
	return puo
}

// SetPeriod sets the "period" field.
func (puo *PseudonymsUpdateOne) SetPeriod(i int) *PseudonymsUpdateOne {
	puo.mutation.ResetPeriod()
	puo.mutation.SetPeriod(i)
	return puo
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (puo *PseudonymsUpdateOne) SetNillablePeriod(i *int) *PseudonymsUpdateOne {
	if i != nil {
		puo.SetPeriod(*i)
	}
	return puo
}

// AddPeriod adds i to the "period" field.
func (puo *PseudonymsUpdateOne) AddPeriod(i int) *PseudonymsUpdateOne {
	puo.mutation.AddPeriod(i)
	return puo
}

// Mutation returns the PseudonymsMutation object of the builder.
func (puo *PseudonymsUpdateOne) Mutation() *PseudonymsMutation {
	return puo.mutation
}

// Where appends a list predicates to the PseudonymsUpdate builder.
func (puo *PseudonymsUpdateOne) Where(ps ...predicate.Pseudonyms) *PseudonymsUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PseudonymsUpdateOne) Select(field string, fields ...string) *PseudonymsUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Pseudonyms entity.
func (puo *PseudonymsUpdateOne) Save(ctx context.Context) (*Pseudonyms, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PseudonymsUpdateOne) SaveX(ctx context.Context) *Pseudonyms {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PseudonymsUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PseudonymsUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PseudonymsUpdateOne) sqlSave(ctx context.Context) (_node *Pseudonyms, err error) {
	_spec := sqlgraph.NewUpdateSpec(pseudonyms.Table, pseudonyms.Columns, sqlgraph.NewFieldSpec(pseudonyms.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pseudonyms.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pseudonyms.FieldID)
		for _, f := range fields {
			if !pseudonyms.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pseudonyms.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Nym(); ok {
		_spec.SetField(pseudonyms.FieldNym, field.TypeBytes, value)
	}
	if value, ok := puo.mutation.Count(); ok {
		_spec.SetField(pseudonyms.FieldCount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedCount(); ok {
		_spec.AddField(pseudonyms.FieldCount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Period(); ok {
		_spec.SetField(pseudonyms.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedPeriod(); ok {
		_spec.AddField(pseudonyms.FieldPeriod, field.TypeInt, value)
	}
	_node = &Pseudonyms{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pseudonyms.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
