// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/verifier/ent/pseudonyms"
)

// PseudonymsCreate is the builder for creating a Pseudonyms entity.
type PseudonymsCreate struct {
	config
	mutation *PseudonymsMutation
	hooks    []Hook
}

// SetNym sets the "nym" field.
func (pc *PseudonymsCreate) SetNym(b []byte) *PseudonymsCreate {
	pc.mutation.SetNym(b)
	return pc
}

// SetCount sets the "count" field.
func (pc *PseudonymsCreate) SetCount(i int) *PseudonymsCreate {
	pc.mutation.SetCount(i)
	return pc
}

// SetPeriod sets the "period" field.
func (pc *PseudonymsCreate) SetPeriod(i int) *PseudonymsCreate {
	pc.mutation.SetPeriod(i)
	return pc
}

// Mutation returns the PseudonymsMutation object of the builder.
func (pc *PseudonymsCreate) Mutation() *PseudonymsMutation {
	return pc.mutation
}

// Save creates the Pseudonyms in the database.
func (pc *PseudonymsCreate) Save(ctx context.Context) (*Pseudonyms, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PseudonymsCreate) SaveX(ctx context.Context) *Pseudonyms {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PseudonymsCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PseudonymsCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PseudonymsCreate) check() error {
	if _, ok := pc.mutation.Nym(); !ok {
		return &ValidationError{Name: "nym", err: errors.New(`ent: missing required field "Pseudonyms.nym"`)}
	}
	if _, ok := pc.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Pseudonyms.count"`)}
	}
	if _, ok := pc.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "Pseudonyms.period"`)}
	}
	return nil
}

func (pc *PseudonymsCreate) sqlSave(ctx context.Context) (*Pseudonyms, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PseudonymsCreate) createSpec() (*Pseudonyms, *sqlgraph.CreateSpec) {
	var (
		_node = &Pseudonyms{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(pseudonyms.Table, sqlgraph.NewFieldSpec(pseudonyms.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Nym(); ok {
		_spec.SetField(pseudonyms.FieldNym, field.TypeBytes, value)
		_node.Nym = value
	}
	if value, ok := pc.mutation.Count(); ok {
		_spec.SetField(pseudonyms.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if value, ok := pc.mutation.Period(); ok {
		_spec.SetField(pseudonyms.FieldPeriod, field.TypeInt, value)
		_node.Period = value
	}
	return _node, _spec
}

// PseudonymsCreateBulk is the builder for creating many Pseudonyms entities in bulk.
type PseudonymsCreateBulk struct {
	config
	err      error
	builders []*PseudonymsCreate
}

// Save creates the Pseudonyms entities in the database.
func (pcb *PseudonymsCreateBulk) Save(ctx context.Context) ([]*Pseudonyms, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Pseudonyms, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PseudonymsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PseudonymsCreateBulk) SaveX(ctx context.Context) []*Pseudonyms {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PseudonymsCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PseudonymsCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
