// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/verifier/ent/pseudonyms"
)

// Pseudonyms is the model entity for the Pseudonyms schema.
type Pseudonyms struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Nym holds the value of the "nym" field.
	Nym []byte `json:"nym,omitempty"`
	// Count holds the value of the "count" field.
	Count int `json:"count,omitempty"`
	// Period holds the value of the "period" field.
	Period       int `json:"period,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pseudonyms) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pseudonyms.FieldNym:
			values[i] = new([]byte)
		case pseudonyms.FieldID, pseudonyms.FieldCount, pseudonyms.FieldPeriod:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pseudonyms fields.
func (ps *Pseudonyms) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pseudonyms.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ps.ID = int(value.Int64)
		case pseudonyms.FieldNym:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nym", values[i])
			} else if value != nil {
				ps.Nym = *value
			}
		case pseudonyms.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				ps.Count = int(value.Int64)
			}
		case pseudonyms.FieldPeriod:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				ps.Period = int(value.Int64)
			}
		default:
			ps.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pseudonyms.
// This includes values selected through modifiers, order, etc.
func (ps *Pseudonyms) Value(name string) (ent.Value, error) {
	return ps.selectValues.Get(name)
}

// Update returns a builder for updating this Pseudonyms.
// Note that you need to call Pseudonyms.Unwrap() before calling this method if this Pseudonyms
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *Pseudonyms) Update() *PseudonymsUpdateOne {
	return NewPseudonymsClient(ps.config).UpdateOne(ps)
}

// Unwrap unwraps the Pseudonyms entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *Pseudonyms) Unwrap() *Pseudonyms {
	_tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pseudonyms is not a transactional entity")
	}
	ps.config.driver = _tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *Pseudonyms) String() string {
	var builder strings.Builder
	builder.WriteString("Pseudonyms(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ps.ID))
	builder.WriteString("nym=")
	builder.WriteString(fmt.Sprintf("%v", ps.Nym))
	builder.WriteString(", ")
	builder.WriteString("count=")
	builder.WriteString(fmt.Sprintf("%v", ps.Count))
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(fmt.Sprintf("%v", ps.Period))
	builder.WriteByte(')')
	return builder.String()
}

// PseudonymsSlice is a parsable slice of Pseudonyms.
type PseudonymsSlice []*Pseudonyms
