// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/akakou/zk-ban-system/core/verifier/ent/predicate"
	"github.com/akakou/zk-ban-system/core/verifier/ent/pseudonyms"
)

// PseudonymsDelete is the builder for deleting a Pseudonyms entity.
type PseudonymsDelete struct {
	config
	hooks    []Hook
	mutation *PseudonymsMutation
}

// Where appends a list predicates to the PseudonymsDelete builder.
func (pd *PseudonymsDelete) Where(ps ...predicate.Pseudonyms) *PseudonymsDelete {
	pd.mutation.Where(ps...)
	return pd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pd *PseudonymsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pd.sqlExec, pd.mutation, pd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pd *PseudonymsDelete) ExecX(ctx context.Context) int {
	n, err := pd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pd *PseudonymsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pseudonyms.Table, sqlgraph.NewFieldSpec(pseudonyms.FieldID, field.TypeInt))
	if ps := pd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pd.mutation.done = true
	return affected, err
}

// PseudonymsDeleteOne is the builder for deleting a single Pseudonyms entity.
type PseudonymsDeleteOne struct {
	pd *PseudonymsDelete
}

// Where appends a list predicates to the PseudonymsDelete builder.
func (pdo *PseudonymsDeleteOne) Where(ps ...predicate.Pseudonyms) *PseudonymsDeleteOne {
	pdo.pd.mutation.Where(ps...)
	return pdo
}

// Exec executes the deletion query.
func (pdo *PseudonymsDeleteOne) Exec(ctx context.Context) error {
	n, err := pdo.pd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pseudonyms.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdo *PseudonymsDeleteOne) ExecX(ctx context.Context) {
	if err := pdo.Exec(ctx); err != nil {
		panic(err)
	}
}
