// Code generated by ent, DO NOT EDIT.

package idtoken

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the idtoken type in the database.
	Label = "id_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdToken holds the string denoting the idtoken field in the database.
	FieldIdToken = "id_token"
	// Table holds the table name of the idtoken in the database.
	Table = "id_tokens"
)

// Columns holds all SQL columns for idtoken fields.
var Columns = []string{
	FieldID,
	FieldIdToken,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the IDToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIdToken orders the results by the idToken field.
func ByIdToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdToken, opts...).ToFunc()
}
