// Code generated by ent, DO NOT EDIT.

package idtoken

import (
	"entgo.io/ent/dialect/sql"
	"github.com/akakou/zk-ban-system/core/gm/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IDToken {
	return predicate.IDToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IDToken {
	return predicate.IDToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IDToken {
	return predicate.IDToken(sql.FieldLTE(FieldID, id))
}

// IdToken applies equality check predicate on the "idToken" field. It's identical to IdTokenEQ.
func IdToken(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldEQ(FieldIdToken, v))
}

// IdTokenEQ applies the EQ predicate on the "idToken" field.
func IdTokenEQ(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldEQ(FieldIdToken, v))
}

// IdTokenNEQ applies the NEQ predicate on the "idToken" field.
func IdTokenNEQ(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldNEQ(FieldIdToken, v))
}

// IdTokenIn applies the In predicate on the "idToken" field.
func IdTokenIn(vs ...string) predicate.IDToken {
	return predicate.IDToken(sql.FieldIn(FieldIdToken, vs...))
}

// IdTokenNotIn applies the NotIn predicate on the "idToken" field.
func IdTokenNotIn(vs ...string) predicate.IDToken {
	return predicate.IDToken(sql.FieldNotIn(FieldIdToken, vs...))
}

// IdTokenGT applies the GT predicate on the "idToken" field.
func IdTokenGT(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldGT(FieldIdToken, v))
}

// IdTokenGTE applies the GTE predicate on the "idToken" field.
func IdTokenGTE(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldGTE(FieldIdToken, v))
}

// IdTokenLT applies the LT predicate on the "idToken" field.
func IdTokenLT(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldLT(FieldIdToken, v))
}

// IdTokenLTE applies the LTE predicate on the "idToken" field.
func IdTokenLTE(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldLTE(FieldIdToken, v))
}

// IdTokenContains applies the Contains predicate on the "idToken" field.
func IdTokenContains(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldContains(FieldIdToken, v))
}

// IdTokenHasPrefix applies the HasPrefix predicate on the "idToken" field.
func IdTokenHasPrefix(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldHasPrefix(FieldIdToken, v))
}

// IdTokenHasSuffix applies the HasSuffix predicate on the "idToken" field.
func IdTokenHasSuffix(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldHasSuffix(FieldIdToken, v))
}

// IdTokenEqualFold applies the EqualFold predicate on the "idToken" field.
func IdTokenEqualFold(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldEqualFold(FieldIdToken, v))
}

// IdTokenContainsFold applies the ContainsFold predicate on the "idToken" field.
func IdTokenContainsFold(v string) predicate.IDToken {
	return predicate.IDToken(sql.FieldContainsFold(FieldIdToken, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IDToken) predicate.IDToken {
	return predicate.IDToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IDToken) predicate.IDToken {
	return predicate.IDToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IDToken) predicate.IDToken {
	return predicate.IDToken(sql.NotPredicates(p))
}
