// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)
