// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Pseudonyms is the predicate function for pseudonyms builders.
type Pseudonyms func(*sql.Selector)
